export type InvestigationNarrative = { uncertainty: string; nextObservation: string };
export type PreservationNarrative = { reading: string; nextStep: string };
type NarrativeSeed = InvestigationNarrative & PreservationNarrative;

const narratives: Record<string, NarrativeSeed> = {
  'product-direction': seed('Prioridade, problema e resultado esperado nem sempre chegam juntos a quem executa; ainda competem falta de direção, contexto retido e decisão sem revisão.', 'Reconstrua a última prioridade relevante: quem explicou o problema, qual resultado justificou o trabalho, o que pôde ser contestado e quando a decisão foi revista.', 'Problema, resultado esperado e limites da decisão chegam juntos ao trabalho e continuam disponíveis quando surgem escolhas.', 'Acompanhe a próxima mudança de prioridade; investigue se ela voltar a chegar como prazo ou solução pronta, sem resultado e trade-off explícitos.'),
  'discovery-validation': seed('Uma ideia pode avançar antes de o problema e a resposta das pessoas usuárias ficarem claros; ainda competem falta de acesso, tempo e decisão fechada cedo.', 'Reconstrua a última ideia levada à construção: qual dúvida existia, que contato ou teste ocorreu antes e o que mudou no recorte depois.', 'Dúvidas relevantes são testadas cedo e a evidência de uso consegue reduzir, alterar ou interromper o que seria construído.', 'Observe a próxima hipótese; investigue se validação voltar a acontecer apenas depois da entrega ou sem poder alterar o compromisso.'),
  'portfolio-management': seed('Iniciativas disputam pessoas e investimento sem comparação comum de resultado, custo de atraso e trabalho em andamento; a origem da disputa ainda não está isolada.', 'Reconstrua a última decisão de iniciar, continuar ou interromper uma iniciativa: quais resultados e custos foram comparados e quem pôde retirar trabalho do portfólio.', 'Novos investimentos são comparados com resultados anteriores e trabalho em andamento; continuidade e interrupção são decisões reais.', 'Acompanhe a próxima entrada; investigue se novo trabalho for apenas somado, sem rever capacidade, resultado ou iniciativa anterior.'),
  'planning-refinement': seed('Riscos, dependências ou critérios aparecem depois de o compromisso já estar assumido; ainda competem pressa, pouca colaboração e solução fechada cedo demais.', 'Reconstrua o último trabalho que mudou muito depois de iniciado: o que ainda não era conhecido, quem poderia ter visto e quando o compromisso começou a contar.', 'Problema, exemplos, riscos e dependências são entendidos antes do compromisso, sem fingir que toda incerteza desapareceu.', 'Observe o próximo item iniciado; investigue se prazo e tempo de entrega começarem antes de existir entendimento compartilhado do problema e dos riscos.'),
  'work-management': seed('Trabalho é acumulado, bloqueado ou iniciado em paralelo sem decisão explícita sobre o que deixa de ser feito; ainda competem prioridade, dependência e limite de trabalho.', 'Reconstrua a última semana com bloqueio ou urgência: quanto trabalho estava aberto, o que esperou, quem decidiu parar ou trocar prioridade e qual foi a consequência.', 'Trabalho e bloqueios ficam visíveis, e iniciar algo novo exige uma escolha explícita sobre capacidade e prioridade.', 'Acompanhe a próxima urgência; investigue se o grupo voltar a absorver tudo, esconder espera ou depender de uma pessoa para perseguir bloqueios.'),
  'continuous-integration': seed('Mudanças permanecem separadas e encontram conflitos tarde; ainda competem retorno técnico lento, política de lote, fronteira entre times e acoplamento do sistema.', 'Reconstrua a última mudança que demorou a encontrar a versão compartilhada: quanto tempo ficou separada, o que impediu integrar antes e qual conflito apareceu.', 'Mudanças pequenas encontram a versão compartilhada cedo e recebem retorno enquanto o contexto ainda está fresco.', 'Acompanhe a próxima mudança comum; investigue se ela voltar a ficar dias isolada ou exigir uma janela coordenada para encontrar as demais.'),
  'release-feedback': seed('Há demora entre uma mudança pronta, sua exposição e o primeiro retorno útil; ainda competem lote, controle de risco, sinal pouco confiável e decisão que não reabre.', 'Reconstrua a última liberação: quando a mudança ficou pronta, quando chegou às pessoas, qual foi o primeiro sinal de efeito e que decisão ele alterou.', 'Implantar, expor e aprender ocorrem em passos controlados; o retorno chega a tempo de mudar a decisão.', 'Acompanhe a próxima liberação; investigue se mudanças prontas voltarem a esperar um lote ou se o retorno chegar sem alterar produto ou operação.'),
  'sustainable-design': seed('Uma área fica mais difícil de alterar e dependente de especialistas; ainda competem falta de tempo, desenho acoplado e conhecimento concentrado.', 'Reconstrua a última mudança pequena que cresceu: quais partes precisaram mudar, quem explicou o caminho e que custo ficou para depois.', 'Mudanças comuns permanecem pequenas, o desenho pode ser explicado por mais de uma pessoa e o custo futuro entra na decisão atual.', 'Observe a próxima alteração na mesma área; investigue se ela voltar a exigir muitas partes, contornos ou a presença de uma pessoa específica.'),
  'quality-strategy': seed('Riscos são descobertos tarde ou protegidos sempre do mesmo modo; ainda competem critérios tardios, pouca testabilidade e responsabilidade concentrada em qualidade.', 'Reconstrua o último defeito relevante: quando o risco poderia ter sido percebido, qual proteção existia em cada etapa e por que a falha apareceu tarde.', 'Cada risco recebe proteção próxima de onde nasce, sem depender de uma fase final para descobrir o comportamento esperado.', 'Acompanhe a próxima mudança arriscada; investigue se qualidade voltar a receber uma versão pronta para descobrir critérios ou executar quase toda a proteção.'),
  'sdlc-automation': seed('O retorno técnico é lento, instável ou incompleto; ainda competem cobertura inadequada, ambiente inconsistente e automação que interrompe sem gerar confiança.', 'Reconstrua a última falha que escapou ou demorou a ser entendida: qual verificação poderia detectá-la, quanto demorou e se outra pessoa repetiu o resultado.', 'Verificações repetíveis devolvem informação confiável enquanto a mudança ainda é pequena e outra pessoa consegue reproduzir a falha.', 'Observe a próxima mudança; investigue se o retorno voltar a ser lento, intermitente ou depender de conferência manual para ser acreditado.'),
  'technical-capability': seed('O conhecimento necessário está fora do alcance do trabalho ou concentrado em poucas pessoas; ainda competem lacuna real, falta de prática, carga e bloqueio organizacional.', 'Reconstrua o último trabalho que parou por conhecimento: o que precisava ser feito, onde estava a experiência, quanto tempo levou para acessá-la e o que o grupo aprendeu.', 'A competência necessária entra no fluxo por prática acompanhada, colaboração ou limites seguros, sem criar fila permanente em especialistas.', 'Acompanhe o próximo tema novo; investigue se o grupo voltar a esperar uma pessoa, fornecedor ou treinamento sem oportunidade de aplicar o aprendizado.'),
  'domain-alignment': seed('Termos, responsabilidades ou limites técnicos divergem do trabalho real; ainda competem linguagem desalinhada, fronteira ruim e responsabilidade fragmentada.', 'Reconstrua a última mudança entre áreas: quais termos geraram dúvida, quantos responsáveis decidiram e onde a responsabilidade deixou de acompanhar o resultado.', 'Linguagem, limites do sistema e responsabilidade acompanham a jornada de negócio e tornam mudanças locais compreensíveis.', 'Observe a próxima mudança transversal; investigue se o mesmo conceito voltar a significar coisas diferentes ou se ninguém responder pelo resultado completo.'),
  'architecture-decisions': seed('Decisões de desenho são difíceis de explicar, revisar ou desfazer; ainda competem contexto perdido, autoridade concentrada e escolha orientada por prestígio.', 'Reconstrua a última decisão técnica relevante: qual problema protegia, que alternativas foram consideradas, quem decidiu e o que faria a escolha ser revista.', 'Decisões relevantes registram problema, escolhas, responsável e condição de revisão em linguagem acessível a quem será afetado.', 'Acompanhe a próxima decisão; investigue se a solução voltar a aparecer sem problema explícito, alternativas ou condição de mudança.'),
  evolvability: seed('Mudanças comuns exigem coordenação, etapas ou componentes demais; ainda competem acoplamento técnico, compatibilidade frágil e fronteiras organizacionais.', 'Reconstrua a última mudança que exigiu coordenação ampla: quais partes mudaram juntas, por que não puderam evoluir separadamente e onde o risco aumentou.', 'O sistema aceita mudanças pequenas e reversíveis sem multiplicar coordenação, risco e custo a cada nova necessidade.', 'Observe a próxima mudança comum; investigue se ela voltar a crescer por dependências, exigir calendário conjunto ou não oferecer reversão segura.'),
  'integration-data': seed('Interfaces ou significados compartilhados mudam sem compatibilidade e visibilidade suficientes; ainda competem origem ambígua, consumidores desconhecidos e verificação tardia.', 'Reconstrua a última mudança de interface ou dado compartilhado: quem consumia, como soube, que versões coexistiram e onde a incompatibilidade apareceu.', 'Interfaces e dados compartilhados possuem responsáveis e evoluem de modo compatível, verificável e visível para consumidores.', 'Acompanhe a próxima mudança compartilhada; investigue se consumidores forem descobertos apenas depois ou se versões precisarem mudar ao mesmo tempo.'),
  'observability-practice': seed('Há dificuldade para investigar impacto; ainda competem informações ausentes, acesso insuficiente e conhecimento distribuído entre pessoas.', 'Reconstrua um incidente recente: qual pergunta precisava ser respondida, quais informações estavam acessíveis, quem conseguiu interpretá-las e onde a investigação parou.', 'O grupo relaciona mudança, comportamento técnico e impacto sem procurar pessoas ou dados sensíveis por tentativa.', 'Acompanhe o próximo incidente; investigue se a explicação voltar a depender de buscas separadas, acesso direto ou alguém que conhece atalhos.'),
  'reliability-practice': seed('Confiabilidade compete com entrega sem um limite de risco compartilhado; ainda competem impacto invisível, objetivo inadequado e falta de autoridade para interromper.', 'Reconstrua a última decisão entre seguir entregando e tratar uma degradação: qual impacto era conhecido, que limite orientou a escolha e quem mudou a prioridade.', 'Impacto e risco aceitável orientam capacidade e ritmo de mudança; degradação relevante consegue alterar prioridade.', 'Observe a próxima degradação; investigue se médias tranquilizadoras ou pressão de prazo voltarem a impedir uma decisão proporcional ao impacto.'),
  'incident-management': seed('Detecção, encaminhamento ou contenção dependem de relações pessoais e caminhos variáveis; ainda competem responsabilidade, classificação, informação e política.', 'Reconstrua o último incidente relevante: quem percebeu, quanto tempo levou até o responsável, como o impacto foi contido e qual mudança reduziu recorrência.', 'Incidentes encontram rapidamente quem pode agir, preservam contenção segura e geram mudança verificável no sistema.', 'Acompanhe o próximo incidente; investigue se ele voltar a procurar responsáveis informalmente, alterar o ambiente sem reconciliação ou encerrar sem aprendizado.'),
  'cloud-reliability': seed('A recuperação é presumida ou depende de especialistas; ainda competem procedimento desatualizado, cópia inadequada e dependência não exercitada.', 'Reconstrua o último teste ou necessidade real de recuperação: o que foi restaurado, por quem, em quanto tempo e qual parte não pôde ser demonstrada.', 'Recuperação é exercitada com resultado observável, dependências conhecidas e tempo compatível com o impacto aceito.', 'Acompanhe o próximo exercício; investigue se a confiança voltar a depender apenas de configuração declarada, documento antigo ou pessoa específica.'),
  'platform-autonomy': seed('Capacidades comuns chegam por fila, ajuda recorrente ou contorno local; ainda competem caminho desconhecido, inacessível, inadequado e sem suporte.', 'Reconstrua o último pedido de ambiente, acesso ou capacidade comum: como o caminho foi descoberto, onde houve espera, quem executou e que exceção apareceu.', 'Times obtêm capacidades comuns por um caminho compreensível, seguro e adequado, com ajuda e exceção visíveis quando necessárias.', 'Observe o próximo pedido; investigue se ele voltar a exigir chamado, herói, documentação sem caminho executável ou contorno fora do suporte.'),
  'reproducible-infrastructure': seed('Ambientes ou configurações divergem da origem conhecida; ainda competem mudança manual, fonte ambígua e exceção não reconciliada.', 'Reconstrua a última alteração de ambiente: onde começou, como chegou ao destino, se outra pessoa conseguiu reproduzi-la e o que ficou diferente da fonte.', 'Ambientes e configurações nascem de uma origem verificável e exceções urgentes retornam a essa origem depois da contenção.', 'Acompanhe a próxima alteração; investigue se alguém voltar a mudar diretamente o ambiente ou se houver mais de uma versão considerada válida.'),
  'cloud-efficiency': seed('Decisões operacionais não usam uma leitura comum de custo e efeito; ainda competem falta de dados, autoridade e rotina de revisão.', 'Reconstrua uma decisão recente de capacidade ou custo: qual informação existia, quem podia decidir, que escolha foi aceita e qual efeito foi revisto depois.', 'Custo, uso e impacto orientam decisões conjuntas; otimização não fica isolada em alerta nem prejudica confiabilidade sem escolha explícita.', 'Acompanhe a próxima variação; investigue se o custo voltar a ser apenas comunicado ou otimizado localmente sem decisão sobre efeito e risco.'),
  'software-security': seed('O risco nem sempre altera o caminho da mudança; ainda competem falta de reconhecimento, autoridade e meio acessível de proteção.', 'Reconstrua uma mudança recente com risco relevante: quando ele apareceu, quem podia mudar o desenho e qual proteção foi aplicada ou dispensada.', 'Risco relevante aparece cedo, altera desenho e verificações e possui responsável capaz de decidir antes da liberação.', 'Observe a próxima mudança com dado, acesso ou confiança; investigue se segurança voltar a aparecer apenas em alerta tardio ou aprovação sem risco nomeado.'),
  'cloud-security': seed('Acesso amplo, credencial difícil de operar ou trilha incompleta reaparecem; ainda competem desenho de identidade, política, ferramenta e exceção operacional.', 'Reconstrua a última concessão ou uso de acesso sensível: quem pediu, qual escopo recebeu, como foi usado e quando a necessidade deixou de existir.', 'Pessoas e sistemas recebem somente o acesso necessário, por tempo e finalidade conhecidos, com uso rastreável e remoção verificável.', 'Acompanhe o próximo acesso; investigue se segredo voltar ao código ou conversa, se privilégio ficar permanente ou se ninguém explicar seu uso.'),
  'team-ownership': seed('Responsabilidade é fragmentada, um serviço fica sem dono ou a mudança atravessa agendas independentes; ainda competem fronteira, prioridade e autoridade.', 'Reconstrua a última mudança ou incidente entre times: quem respondia pelo resultado, onde a decisão parou e qual parte ficou sem responsável claro.', 'Responsabilidade acompanha resultado e operação de ponta a ponta; dependências possuem interface e decisão conhecidas.', 'Observe a próxima mudança transversal; investigue se ela voltar a depender de coordenação informal, escalada ou artefato que vários alteram e ninguém mantém.'),
  'enabling-governance': seed('Controles tratam riscos diferentes do mesmo modo ou transferem responsabilidade sem reduzir risco; ainda competem obrigação legítima, confiança técnica e política desatualizada.', 'Reconstrua a última mudança pequena que esperou aprovação: qual risco a etapa protegia, quem tinha autoridade e o que mudaria para uma alteração maior.', 'Controles são proporcionais ao risco, deixam a decisão rastreável e permitem caminho simples para mudanças pequenas e reversíveis.', 'Acompanhe a próxima mudança de baixo risco; investigue se ela voltar a esperar o lote das grandes ou depender de exceção informal.'),
  'leadership-management': seed('Direção, capacidade ou escalada não removem um gargalo reconhecido; ainda competem prioridade, incentivo, autoridade e desenho organizacional.', 'Reconstrua o último problema que o time não podia resolver: que evidência chegou à liderança, qual decisão foi tomada, que capacidade foi reservada e o que mudou.', 'Liderança transforma evidência de gargalo em prioridade, autoridade e capacidade para mudar o sistema, acompanhando o efeito depois.', 'Observe o próximo impedimento sistêmico; investigue se ele voltar ao time sem decisão, ganhar apenas cobrança ou abrir ações sem capacidade.'),
  collaboration: seed('Contexto chega por partes, especialidades entram tarde ou dependências exigem alinhamento contínuo; ainda competem interface ruim, poder assimétrico e responsabilidade fragmentada.', 'Reconstrua o último trabalho com várias funções ou times: quando cada um entrou, que contexto faltou, onde houve espera e quem fechou a decisão.', 'As pessoas necessárias entram enquanto ainda podem mudar a decisão; interfaces tornam pedido, parceria, espera e responsabilidade explícitos.', 'Acompanhe a próxima mudança compartilhada; investigue se contexto voltar a ser transferido no final ou se comunicação extra apenas compensar uma fronteira ruim.'),
  'organizational-learning': seed('Problemas reconhecidos reaparecem sem ação sustentada; ainda competem falta de capacidade, autonomia, foco e segurança para expor a causa.', 'Reconstrua a última ação de melhoria que perdeu continuidade: quem assumiu, que capacidade recebeu, quando o efeito seria revisto e o que impediu fechar o ciclo.', 'Aprendizado produz uma mudança pequena com responsável, capacidade, revisão de efeito e disseminação quando funciona.', 'Acompanhe a próxima ação; investigue se ela voltar a virar lista sem limite, cerimônia sem decisão ou reação apenas depois de crise.'),
};

function seed(uncertainty: string, nextObservation: string, reading: string, nextStep: string): NarrativeSeed {
  return { uncertainty: `As respostas mostram que ${uncertainty}`, nextObservation, reading, nextStep };
}

export function investigationFor(capabilityId: string): InvestigationNarrative {
  const item = narrativeFor(capabilityId);
  return { uncertainty: item.uncertainty, nextObservation: item.nextObservation };
}

export function preservationFor(capabilityId: string): PreservationNarrative {
  const item = narrativeFor(capabilityId);
  return { reading: item.reading, nextStep: `Preserve este comportamento e não acrescente intervenção sem um problema observado. ${item.nextStep}` };
}

function narrativeFor(capabilityId: string): NarrativeSeed {
  const item = narratives[capabilityId];
  if (!item) throw new Error(`Narrativa operacional ausente para a capacidade ${capabilityId}.`);
  return item;
}
