export type InvestigationNarrative = { uncertainty: string; nextObservation: string };
export type PreservationNarrative = { reading: string; nextStep: string };
type NarrativeSeed = InvestigationNarrative & PreservationNarrative;

const narratives: Record<string, NarrativeSeed> = {
  'product-direction': seed('Quem executa recebe prazo ou solução, mas nem sempre o problema e o resultado esperado. Ainda não dá para dizer se falta direção, se o contexto ficou com outra pessoa ou se a decisão já veio fechada sem revisão.', 'Reconstrua a última prioridade relevante: quem explicou o problema, qual resultado justificou o trabalho, o que pôde ser contestado e quando a decisão foi revista.', 'Problema, resultado esperado e limites da decisão chegam juntos ao trabalho e continuam disponíveis quando surgem escolhas.', 'Acompanhe a próxima mudança de prioridade; investigue se ela voltar a chegar como prazo ou solução pronta, sem resultado e trade-off explícitos.'),
  'discovery-validation': seed('Uma ideia pode virar construção antes de alguém conversar com quem usa ou testar a dúvida. Ainda não dá para dizer se faltou acesso, se não houve tempo ou se a decisão já estava fechada.', 'Reconstrua a última ideia levada à construção: qual dúvida existia, que contato ou teste ocorreu antes e o que mudou no recorte depois.', 'Dúvidas relevantes são testadas cedo e a evidência de uso consegue reduzir, alterar ou interromper o que seria construído.', 'Observe a próxima hipótese; investigue se validação voltar a acontecer apenas depois da entrega ou sem poder alterar o compromisso.'),
  'portfolio-management': seed('Iniciativas disputam pessoas e investimento sem comparar resultado, custo de atraso e trabalho em andamento. A origem dessa disputa ainda não está isolada.', 'Reconstrua a última decisão de iniciar, continuar ou interromper uma iniciativa: quais resultados e custos foram comparados e quem pôde retirar trabalho do portfólio.', 'Novos investimentos são comparados com resultados anteriores e trabalho em andamento; continuidade e interrupção são decisões reais.', 'Acompanhe a próxima entrada; investigue se novo trabalho for apenas somado, sem rever capacidade, resultado ou iniciativa anterior.'),
  'planning-refinement': seed('O compromisso começa e só depois aparecem risco, dependência ou critério. Ainda não dá para dizer se foi pressa, se quem precisava ver não entrou ou se a solução já veio pronta.', 'Reconstrua o último trabalho que mudou muito depois de iniciado: o que ainda não era conhecido, quem poderia ter visto e quando o compromisso começou a contar.', 'Problema, exemplos, riscos e dependências são entendidos antes do compromisso, sem fingir que toda incerteza desapareceu.', 'Observe o próximo item iniciado; investigue se prazo e tempo de entrega começarem antes de existir entendimento compartilhado do problema e dos riscos.'),
  'work-management': seed('O grupo acumula, bloqueia ou inicia trabalho em paralelo sem decidir o que deixa de ser feito. Ainda não dá para dizer se o problema é prioridade, dependência externa ou ausência de limite de trabalho aberto.', 'Reconstrua a última semana com bloqueio ou urgência: quanto trabalho estava aberto, o que esperou, quem decidiu parar ou trocar prioridade e qual foi a consequência.', 'Trabalho e bloqueios ficam visíveis, e iniciar algo novo exige uma escolha explícita sobre capacidade e prioridade.', 'Acompanhe a próxima urgência; investigue se o grupo voltar a absorver tudo, esconder espera ou depender de uma pessoa para perseguir bloqueios.'),
  'continuous-integration': seed('O trabalho de cada pessoa fica separado. O conflito só aparece quando alguém junta as partes. Ainda não dá para dizer se a verificação demora, se a regra obriga a juntar tudo de uma vez, se os times só se encontram no fim ou se o desenho força muita gente a mudar junto.', 'Reconstrua a última mudança que demorou a encontrar a versão compartilhada: quanto tempo ficou separada, o que impediu integrar antes e qual conflito apareceu.', 'Mudanças pequenas encontram a versão compartilhada cedo e recebem retorno enquanto o contexto ainda está fresco.', 'Acompanhe a próxima mudança comum; investigue se ela voltar a ficar dias isolada ou exigir uma janela coordenada para encontrar as demais.'),
  'release-feedback': seed('A mudança fica pronta e o primeiro retorno útil demora. Ainda não dá para dizer se ela esperou um lote, se um controle segurou a exposição, se o sinal não é confiável ou se o retorno chega e ninguém reabre a decisão.', 'Reconstrua a última liberação: quando a mudança ficou pronta, quando chegou às pessoas, qual foi o primeiro sinal de efeito e que decisão ele alterou.', 'Implantar, expor e aprender ocorrem em passos controlados; o retorno chega a tempo de mudar a decisão.', 'Acompanhe a próxima liberação; investigue se mudanças prontas voltarem a esperar um lote ou se o retorno chegar sem alterar produto ou operação.'),
  'sustainable-design': seed('Uma área fica mais difícil de alterar e depende de quem já conhece o caminho. Ainda não dá para dizer se faltou tempo para deixar o desenho simples, se as partes estão acopladas ou se o conhecimento ficou em poucas pessoas.', 'Reconstrua a última mudança pequena que cresceu: quais partes precisaram mudar, quem explicou o caminho e que custo ficou para depois.', 'Mudanças comuns permanecem pequenas, o desenho pode ser explicado por mais de uma pessoa e o custo futuro entra na decisão atual.', 'Observe a próxima alteração na mesma área; investigue se ela voltar a exigir muitas partes, contornos ou a presença de uma pessoa específica.'),
  'quality-strategy': seed('O risco aparece tarde ou sempre é tratado do mesmo jeito no fim. Ainda não dá para dizer se o critério chegou depois, se o desenho é difícil de verificar ou se só o time de qualidade carrega a proteção.', 'Reconstrua o último defeito relevante: quando o risco poderia ter sido percebido, qual proteção existia em cada etapa e por que a falha apareceu tarde.', 'Cada risco recebe proteção próxima de onde nasce, sem depender de uma fase final para descobrir o comportamento esperado.', 'Acompanhe a próxima mudança arriscada; investigue se qualidade voltar a receber uma versão pronta para descobrir critérios ou executar quase toda a proteção.'),
  'sdlc-automation': seed('O retorno técnico chega tarde, varia ou não dá para confiar. Ainda não dá para dizer se a verificação não cobre o risco, se o ambiente muda o resultado ou se a automação só interrompe sem explicar.', 'Reconstrua a última falha que escapou ou demorou a ser entendida: qual verificação poderia detectá-la, quanto demorou e se outra pessoa repetiu o resultado.', 'Verificações repetíveis devolvem informação confiável enquanto a mudança ainda é pequena e outra pessoa consegue reproduzir a falha.', 'Observe a próxima mudança; investigue se o retorno voltar a ser lento, intermitente ou depender de conferência manual para ser acreditado.'),
  'technical-capability': seed('O trabalho para porque o conhecimento não está com quem precisa executar. Ainda não dá para dizer se a competência não existe no grupo, se ninguém consegue praticar, se a carga impede aprender ou se a organização bloqueia o acesso.', 'Reconstrua o último trabalho que parou por conhecimento: o que precisava ser feito, onde estava a experiência, quanto tempo levou para acessá-la e o que o grupo aprendeu.', 'A competência necessária entra no fluxo por prática acompanhada, colaboração ou limites seguros, sem criar fila permanente em especialistas.', 'Acompanhe o próximo tema novo; investigue se o grupo voltar a esperar uma pessoa, fornecedor ou treinamento sem oportunidade de aplicar o aprendizado.'),
  'domain-alignment': seed('As pessoas usam os mesmos termos e não falam da mesma coisa; a responsabilidade não acompanha o resultado. Ainda não dá para dizer se é linguagem, fronteira ruim ou dono fragmentado.', 'Reconstrua a última mudança entre áreas: quais termos geraram dúvida, quantos responsáveis decidiram e onde a responsabilidade deixou de acompanhar o resultado.', 'Linguagem, limites do sistema e responsabilidade acompanham a jornada de negócio e tornam mudanças locais compreensíveis.', 'Observe a próxima mudança transversal; investigue se o mesmo conceito voltar a significar coisas diferentes ou se ninguém responder pelo resultado completo.'),
  'architecture-decisions': seed('Uma decisão de desenho é difícil de explicar, revisar ou desfazer. Ainda não dá para dizer se o contexto se perdeu, se só uma pessoa podia decidir ou se a escolha veio por prestígio da solução.', 'Reconstrua a última decisão técnica relevante: qual problema protegia, que alternativas foram consideradas, quem decidiu e o que faria a escolha ser revista.', 'Decisões relevantes registram problema, escolhas, responsável e condição de revisão em linguagem acessível a quem será afetado.', 'Acompanhe a próxima decisão; investigue se a solução voltar a aparecer sem problema explícito, alternativas ou condição de mudança.'),
  evolvability: seed('Uma mudança comum arrasta coordenação, etapas ou componentes demais. Ainda não dá para dizer se as partes estão acopladas, se a compatibilidade é frágil ou se a fronteira entre times obriga todo mundo a se mover junto.', 'Reconstrua a última mudança que exigiu coordenação ampla: quais partes mudaram juntas, por que não puderam evoluir separadamente e onde o risco aumentou.', 'O sistema aceita mudanças pequenas e reversíveis sem multiplicar coordenação, risco e custo a cada nova necessidade.', 'Observe a próxima mudança comum; investigue se ela voltar a crescer por dependências, exigir calendário conjunto ou não oferecer reversão segura.'),
  'integration-data': seed('Uma interface ou um dado compartilhado muda e o outro lado descobre tarde. Ainda não dá para dizer se a origem é ambígua, se os consumidores eram desconhecidos ou se a verificação só acontece no fim.', 'Reconstrua a última mudança de interface ou dado compartilhado: quem consumia, como soube, que versões coexistiram e onde a incompatibilidade apareceu.', 'Interfaces e dados compartilhados possuem responsáveis e evoluem de modo compatível, verificável e visível para consumidores.', 'Acompanhe a próxima mudança compartilhada; investigue se consumidores forem descobertos apenas depois ou se versões precisarem mudar ao mesmo tempo.'),
  'observability-practice': seed('Investigar um impacto exige procurar gente e juntar pedaços. Ainda não dá para dizer se falta informação, se o acesso não chega ou se só algumas pessoas sabem ler o que existe.', 'Reconstrua um incidente recente: qual pergunta precisava ser respondida, quais informações estavam acessíveis, quem conseguiu interpretá-las e onde a investigação parou.', 'O grupo relaciona mudança, comportamento técnico e impacto sem procurar pessoas ou dados sensíveis por tentativa.', 'Acompanhe o próximo incidente; investigue se a explicação voltar a depender de buscas separadas, acesso direto ou alguém que conhece atalhos.'),
  'reliability-practice': seed('Entregar e manter o serviço competem sem um limite de risco compartilhado. Ainda não dá para dizer se o impacto ficou invisível, se o objetivo medido não serve ou se ninguém podia interromper.', 'Reconstrua a última decisão entre seguir entregando e tratar uma degradação: qual impacto era conhecido, que limite orientou a escolha e quem mudou a prioridade.', 'Impacto e risco aceitável orientam capacidade e ritmo de mudança; degradação relevante consegue alterar prioridade.', 'Observe a próxima degradação; investigue se médias tranquilizadoras ou pressão de prazo voltarem a impedir uma decisão proporcional ao impacto.'),
  'incident-management': seed('Detectar, encaminhar ou conter um incidente depende de quem a pessoa conhece. Ainda não dá para dizer se falta responsável, se o impacto foi mal classificado, se a informação não chegou ou se a política impede o caminho direto.', 'Reconstrua o último incidente relevante: quem percebeu, quanto tempo levou até o responsável, como o impacto foi contido e qual mudança reduziu recorrência.', 'Incidentes encontram rapidamente quem pode agir, preservam contenção segura e geram mudança verificável no sistema.', 'Acompanhe o próximo incidente; investigue se ele voltar a procurar responsáveis informalmente, alterar o ambiente sem reconciliação ou encerrar sem aprendizado.'),
  'cloud-reliability': seed('A recuperação é presumida ou só acontece quando o especialista está presente. Ainda não dá para dizer se o procedimento está velho, se a cópia não serve ou se a dependência nunca foi exercitada.', 'Reconstrua o último teste ou necessidade real de recuperação: o que foi restaurado, por quem, em quanto tempo e qual parte não pôde ser demonstrada.', 'Recuperação é exercitada com resultado observável, dependências conhecidas e tempo compatível com o impacto aceito.', 'Acompanhe o próximo exercício; investigue se a confiança voltar a depender apenas de configuração declarada, documento antigo ou pessoa específica.'),
  'platform-autonomy': seed('Ambiente, acesso ou capacidade comum chegam por fila, ajuda de alguém ou um contorno local. Ainda não dá para dizer se o caminho é desconhecido, se existe e ninguém consegue usar, se não serve para o caso ou se só funciona com suporte.', 'Reconstrua o último pedido de ambiente, acesso ou capacidade comum: como o caminho foi descoberto, onde houve espera, quem executou e que exceção apareceu.', 'Times obtêm capacidades comuns por um caminho compreensível, seguro e adequado, com ajuda e exceção visíveis quando necessárias.', 'Observe o próximo pedido; investigue se ele voltar a exigir chamado, herói, documentação sem caminho executável ou contorno fora do suporte.'),
  'reproducible-infrastructure': seed('O ambiente em uso não é o mesmo da origem que o grupo considera válida. Ainda não dá para dizer se alguém mudou na mão, se há mais de uma fonte ou se a urgência nunca voltou para a origem.', 'Reconstrua a última alteração de ambiente: onde começou, como chegou ao destino, se outra pessoa conseguiu reproduzi-la e o que ficou diferente da fonte.', 'Ambientes e configurações nascem de uma origem verificável e exceções urgentes retornam a essa origem depois da contenção.', 'Acompanhe a próxima alteração; investigue se alguém voltar a mudar diretamente o ambiente ou se houver mais de uma versão considerada válida.'),
  'cloud-efficiency': seed('Decisões de capacidade e custo não partem de uma leitura comum de efeito. Ainda não dá para dizer se faltam dados, se ninguém pode decidir ou se não existe rotina de revisão.', 'Reconstrua uma decisão recente de capacidade ou custo: qual informação existia, quem podia decidir, que escolha foi aceita e qual efeito foi revisto depois.', 'Custo, uso e impacto orientam decisões conjuntas; otimização não fica isolada em alerta nem prejudica confiabilidade sem escolha explícita.', 'Acompanhe a próxima variação; investigue se o custo voltar a ser apenas comunicado ou otimizado localmente sem decisão sobre efeito e risco.'),
  'software-security': seed('Um risco relevante pode não mudar o caminho da entrega. Ainda não dá para dizer se ninguém o reconheceu a tempo, se quem viu não podia alterar o desenho ou se não havia um meio acessível de proteger.', 'Reconstrua uma mudança recente com risco relevante: quando ele apareceu, quem podia mudar o desenho e qual proteção foi aplicada ou dispensada.', 'Risco relevante aparece cedo, altera desenho e verificações e possui responsável capaz de decidir antes da liberação.', 'Observe a próxima mudança com dado, acesso ou confiança; investigue se segurança voltar a aparecer apenas em alerta tardio ou aprovação sem risco nomeado.'),
  'cloud-security': seed('Acesso amplo, credencial difícil de operar ou trilha incompleta voltam a aparecer. Ainda não dá para dizer se o desenho de identidade é o problema, se a política obriga o atalho, se a ferramenta não cabe ou se a exceção operacional ficou permanente.', 'Reconstrua a última concessão ou uso de acesso sensível: quem pediu, qual escopo recebeu, como foi usado e quando a necessidade deixou de existir.', 'Pessoas e sistemas recebem somente o acesso necessário, por tempo e finalidade conhecidos, com uso rastreável e remoção verificável.', 'Acompanhe o próximo acesso; investigue se segredo voltar ao código ou conversa, se privilégio ficar permanente ou se ninguém explicar seu uso.'),
  'team-ownership': seed('A responsabilidade se parte: um serviço fica sem dono ou a mudança atravessa agendas que não se encontram. Ainda não dá para dizer se a fronteira está errada, se as prioridades competem ou se ninguém tem autoridade para terminar.', 'Reconstrua a última mudança ou incidente entre times: quem respondia pelo resultado, onde a decisão parou e qual parte ficou sem responsável claro.', 'Responsabilidade acompanha resultado e operação de ponta a ponta; dependências possuem interface e decisão conhecidas.', 'Observe a próxima mudança transversal; investigue se ela voltar a depender de coordenação informal, escalada ou artefato que vários alteram e ninguém mantém.'),
  'enabling-governance': seed('O mesmo controle trata risco pequeno e risco grande, ou transfere a responsabilidade sem reduzir o risco. Ainda não dá para dizer se a obrigação é legítima, se a confiança técnica falta ou se a política ficou desatualizada.', 'Reconstrua a última mudança pequena que esperou aprovação: qual risco a etapa protegia, quem tinha autoridade e o que mudaria para uma alteração maior.', 'Controles são proporcionais ao risco, deixam a decisão rastreável e permitem caminho simples para mudanças pequenas e reversíveis.', 'Acompanhe a próxima mudança de baixo risco; investigue se ela voltar a esperar o lote das grandes ou depender de exceção informal.'),
  'leadership-management': seed('A liderança reconhece o gargalo e ele continua no time. Ainda não dá para dizer se faltou prioridade, se o incentivo puxa para outro lado, se ninguém tinha autoridade ou se o desenho organizacional impede a mudança.', 'Reconstrua o último problema que o time não podia resolver: que evidência chegou à liderança, qual decisão foi tomada, que capacidade foi reservada e o que mudou.', 'Liderança transforma evidência de gargalo em prioridade, autoridade e capacidade para mudar o sistema, acompanhando o efeito depois.', 'Observe o próximo impedimento sistêmico; investigue se ele voltar ao time sem decisão, ganhar apenas cobrança ou abrir ações sem capacidade.'),
  collaboration: seed('O contexto chega por partes, a especialidade entra tarde ou a dependência exige alinhamento o tempo todo. Ainda não dá para dizer se a interface é ruim, se o poder é assimétrico ou se a responsabilidade está fragmentada.', 'Reconstrua o último trabalho com várias funções ou times: quando cada um entrou, que contexto faltou, onde houve espera e quem fechou a decisão.', 'As pessoas necessárias entram enquanto ainda podem mudar a decisão; interfaces tornam pedido, parceria, espera e responsabilidade explícitos.', 'Acompanhe a próxima mudança compartilhada; investigue se contexto voltar a ser transferido no final ou se comunicação extra apenas compensar uma fronteira ruim.'),
  'organizational-learning': seed('O grupo reconhece o problema e ele volta. Ainda não dá para dizer se faltou capacidade para agir, se a decisão está fora do time, se a lista não tem foco ou se ninguém se sente seguro para nomear a causa.', 'Reconstrua a última ação de melhoria que perdeu continuidade: quem assumiu, que capacidade recebeu, quando o efeito seria revisto e o que impediu fechar o ciclo.', 'Aprendizado produz uma mudança pequena com responsável, capacidade, revisão de efeito e disseminação quando funciona.', 'Acompanhe a próxima ação; investigue se ela voltar a virar lista sem limite, cerimônia sem decisão ou reação apenas depois de crise.'),
};

function seed(uncertainty: string, nextObservation: string, reading: string, nextStep: string): NarrativeSeed {
  return { uncertainty, nextObservation, reading, nextStep };
}

export function investigationFor(capabilityId: string): InvestigationNarrative {
  const item = narrativeFor(capabilityId);
  return { uncertainty: item.uncertainty, nextObservation: item.nextObservation };
}

export function preservationFor(capabilityId: string): PreservationNarrative {
  const item = narrativeFor(capabilityId);
  return { reading: item.reading, nextStep: `Preserve este comportamento e não acrescente intervenção sem um problema observado. ${item.nextStep}` };
}

function narrativeFor(capabilityId: string): NarrativeSeed {
  const item = narratives[capabilityId];
  if (!item) throw new Error(`Narrativa operacional ausente para a capacidade ${capabilityId}.`);
  return item;
}
