type FoundationRef = { source: string; principle?: string; why?: string };

export type GuidanceConstraint = 'skill' | 'autonomy' | 'process' | 'structure' | 'platform' | 'incentive' | 'architecture' | 'governance' | 'organization' | 'priority';
export type SolutionKind = 'practice' | 'policy' | 'org-design' | 'platform-capability' | 'tool-class';

export type SolutionGuidance = {
  mechanism: string;
  constraintKind: GuidanceConstraint;
  plainExplanation: string;
  solutionKind: SolutionKind;
  solutionClass: string;
  matureReference: string;
  whyItWorks: string;
  doesNotSolve: string;
  examples: string;
  antiPattern: string;
  metric: string;
  successCriterion: string;
};

const explicit: Record<string, SolutionGuidance> = {
  'feedback-tardio': {
    mechanism: 'A solução acumula antes da primeira prova conjunta, então o desacordo só aparece quando o lote já está grande.',
    constraintKind: 'process',
    plainExplanation: 'O grupo constrói bastante antes de mostrar a hipótese para quem usa ou para as outras disciplinas. Quando o retorno chega, o custo de mudar já subiu. Não é falta de cerimônia: é o intervalo até a primeira evidência capaz de reabrir a decisão.',
    solutionKind: 'practice',
    solutionClass: 'Lote pequeno com uma prova conjunta antes de ampliar a solução',
    matureReference: 'Discovery e evidência de uso',
    whyItWorks: 'O investimento pára enquanto ainda cabe voltar atrás.',
    doesNotSolve: 'Não cria autonomia se o patrocínio não pode ser contestado.',
    examples: 'Uma suposição validável antes da demonstração formal — não um workshop extra.',
    antiPattern: 'Marcar mais alinhamento sem reduzir o que se constrói antes da primeira prova.',
    metric: 'tamanho do lote até o primeiro feedback conjunto e retrabalho depois dele',
    successCriterion: 'a próxima construção valida uma suposição relevante antes da demonstração formal',
  },
  'mudanca-isolada': {
    mechanism: 'Cada alteração fica isolada até um lote grande; o restante do sistema só aparece quando o custo de juntar já cresceu.',
    constraintKind: 'process',
    plainExplanation: 'O trabalho de várias pessoas só se encontra no fim. Incompatibilidades aparecem grandes, o diagnóstico demora e a correção interrompe quem já tinha “terminado”. Não é falta de ferramenta de build: é o hábito de acumular antes de juntar.',
    solutionKind: 'practice',
    solutionClass: 'Integração em tronco com retorno no mesmo dia',
    matureReference: 'Continuous Delivery',
    whyItWorks: 'O conflito aparece enquanto a mudança ainda é pequena e reversível.',
    doesNotSolve: 'Não corrige ownership partido nem ambiente que só existe na máquina de uma pessoa.',
    examples: 'Verificação automatizada no caminho da mudança — a família das esteiras de integração, não a marca da ferramenta.',
    antiPattern: 'Instalar uma esteira e continuar acumulando semanas de trabalho isolado.',
    metric: 'tempo até a primeira composição verificável e retrabalho depois do encontro',
    successCriterion: 'a próxima mudança equivalente encontra o restante no mesmo dia, sem aumento de falhas na junção',
  },
  'integracao-tardia': {
    mechanism: 'Partes da entrega só se encontram depois de decisões já tomadas, então o retrabalho chega tarde.',
    constraintKind: 'process',
    plainExplanation: 'Times avançam em paralelo e só combinam o resultado perto da data. O problema não é “falta de alinhamento”: é o intervalo até a primeira prova de que as partes funcionam juntas.',
    solutionKind: 'practice',
    solutionClass: 'Primeira integração verificável cedo, em lote pequeno',
    matureReference: 'Continuous Delivery',
    whyItWorks: 'O desacordo técnico aparece antes de virar retrabalho de fim de ciclo.',
    doesNotSolve: 'Não substitui um contrato quando o acoplamento obriga todo mundo a mudar ao mesmo tempo.',
    examples: 'Composição frequente com verificação no caminho — não uma cerimônia extra de alinhamento.',
    antiPattern: 'Marcar mais reuniões de sincronização sem reduzir o intervalo até juntar o trabalho.',
    metric: 'intervalo até a primeira integração verificável e retrabalho após o encontro',
    successCriterion: 'o próximo lote encontra as partes enquanto ainda é reversível',
  },
  'integracao-por-janela': {
    mechanism: 'A junção depende de uma janela e de versões combinadas, então o fluxo espera o calendário, não a prontidão.',
    constraintKind: 'process',
    plainExplanation: 'Só se junta quando “todo mundo está pronto” numa data. Enquanto isso, o trabalho acumula e o risco cresce. Organizações maduras separam prontidão da exposição.',
    solutionKind: 'practice',
    solutionClass: 'Verificação contínua fora da janela de liberação',
    matureReference: 'Continuous Delivery',
    whyItWorks: 'A incompatibilidade aparece sem precisar da data oficial de juntas.',
    doesNotSolve: 'Não remove um acoplamento que exige mudar dois sistemas na mesma hora.',
    examples: 'Contrato ou verificação de compatibilidade rodando no fluxo normal.',
    antiPattern: 'Criar uma janela maior em vez de uma prova fora da janela.',
    metric: 'espera até a janela e falhas descobertas só nela',
    successCriterion: 'uma dependência recorrente é verificada fora da janela sem aumentar incidentes na liberação',
  },
  'causa-ferramental-feedback': {
    mechanism: 'O retorno automatizado é lento, instável ou incompleto, então integrar cedo interrompe o trabalho sem produzir confiança.',
    constraintKind: 'platform',
    plainExplanation: 'Juntar cedo só vale se a resposta vier rápido e for confiável. Se a verificação demora ou falha por motivos alheios à mudança, as pessoas acumulam trabalho para não “perder o dia”. Isso é restrição de plataforma e de desenho do caminho, não preguiça.',
    solutionKind: 'platform-capability',
    solutionClass: 'Caminho de verificação rápida e estável o bastante para orientar a decisão',
    matureReference: 'Continuous Delivery',
    whyItWorks: 'O custo de integrar cedo deixa de ser maior do que o custo de esperar.',
    doesNotSolve: 'Não resolve política que obriga lote grande mesmo com retorno rápido.',
    examples: 'Família de verificação no caminho da mudança (compilação, teste de contrato, análise de risco proporcional) — sem eleger fornecedor.',
    antiPattern: 'Comprar mais scanners enquanto a verificação que as pessoas realmente esperam continua lenta ou vermelha à toa.',
    metric: 'duração, instabilidade e vezes em que o grupo segue sem esperar o retorno',
    successCriterion: 'a verificação que mais fazia acumular mudanças passa a ser usada no mesmo dia, sem aumento de escapes',
  },
  'automacao-sem-feedback': {
    mechanism: 'Existe automação, mas o retorno não chega a tempo nem com estabilidade para mudar a decisão da pessoa que alterou o sistema.',
    constraintKind: 'platform',
    plainExplanation: '“Temos automação” não basta. Se o resultado demora ou varia, a pessoa decide no escuro e a automação vira teatro. O alvo é o retorno útil, não a quantidade de scripts.',
    solutionKind: 'platform-capability',
    solutionClass: 'Feedback técnico repetível no tempo da decisão',
    matureReference: 'Continuous Delivery',
    whyItWorks: 'A pessoa só espera o retorno se ele for mais barato do que seguir sem ele.',
    doesNotSolve: 'Não ensina o risco de negócio se a verificação não cobre o que realmente quebra o usuário.',
    examples: 'Esteira ou suíte enxuta no caminho da mudança, com dono da instabilidade.',
    antiPattern: 'Ampliar a suíte sem medir espera e falsos alarmes.',
    metric: 'espera até um retorno acionável e taxa de execuções ignoradas',
    successCriterion: 'a próxima mudança espera o retorno sem aumentar o lote acumulado',
  },
  'causa-processo-lote': {
    mechanism: 'Uma etapa ou política trata riscos diferentes do mesmo jeito, então mudanças pequenas esperam o lote das grandes.',
    constraintKind: 'process',
    plainExplanation: 'O mesmo portão serve para um ajuste mínimo e para uma mudança arriscada. O grupo acumula trabalho para “valer a pena” atravessar. Isso é desenho de controle, não falta de disciplina.',
    solutionKind: 'policy',
    solutionClass: 'Caminho proporcional ao risco para mudança pequena e reversível',
    matureReference: 'Governança habilitadora',
    whyItWorks: 'O controle continua no que é perigoso e para de inflar o que não é.',
    doesNotSolve: 'Não substitui verificação técnica quando o risco é real e ninguém o nomeou.',
    examples: 'Duas classes de risco com guardrail automático na classe baixa.',
    antiPattern: 'Abolir o controle inteiro em vez de diferenciá-lo.',
    metric: 'espera da mudança pequena na etapa e exceções informais para furá-la',
    successCriterion: 'uma mudança reversível atravessa sem a janela do lote, com o risco nomeado',
  },
  'causa-multiplas-fontes': {
    mechanism: 'Mais de um caminho produz a versão considerada válida, então ninguém sabe qual origem reconciliar depois de um incidente ou de uma correção.',
    constraintKind: 'architecture',
    plainExplanation: 'A “versão certa” pode ter saído do console, de um script local ou de um repositório. Na urgência, cada caminho ganha. Depois, o ambiente diverge e a próxima mudança parte de um chão instável.',
    solutionKind: 'tool-class',
    solutionClass: 'Origem única verificável — infraestrutura e versão como declaração reproduzível',
    matureReference: 'Continuous Delivery / GitOps',
    whyItWorks: 'Toda alteração visível tem um lugar para ser revista, revertida e auditada.',
    doesNotSolve: 'Não cria ownership se três times ainda podem alterar o mesmo recurso sem contrato.',
    examples: 'Ferramentas da família de infraestrutura como código e reconciliação declarativa (GitOps), sem eleger marca.',
    antiPattern: 'Comprar a ferramenta e manter o console como caminho paralelo “só na urgência” sem reconciliação.',
    metric: 'caminhos paralelos ainda capazes de produzir a versão válida e divergências após correção emergencial',
    successCriterion: 'um caminho alternativo deixa de promover versão sem proveniência verificável',
  },
  'fonte-nao-confiavel': {
    mechanism: 'A versão em uso não carrega proveniência verificável, então confiança depende de quem empacotou ou de onde o arquivo estava.',
    constraintKind: 'architecture',
    plainExplanation: 'Ninguém prova, com o artefato na mão, de onde ele veio e o que entrou nele. Isso vira discussão e retrabalho, não um dado.',
    solutionKind: 'practice',
    solutionClass: 'Proveniência verificável do artefato promovido',
    matureReference: 'Continuous Delivery',
    whyItWorks: 'A promoção deixa de depender de memória e de cópia informal.',
    doesNotSolve: 'Não acelera um caminho de verificação que continua levando horas.',
    examples: 'Assinatura, identificador e origem única do pacote — classe de cadeia de suprimento, não um produto.',
    antiPattern: 'Exigir um relatório de compliance sem remover o caminho que ainda gera a versão “na mão”.',
    metric: 'artefatos promovidos sem origem inequívoca e tempo para reconciliar “qual é a versão”',
    successCriterion: 'o próximo artefato crítico só avança com proveniência verificável',
  },
  'qualidade-como-fase': {
    mechanism: 'O risco só é tratado quando o trabalho já está “pronto” e entra numa fila especializada, então o feedback chega depois do custo de mudar ter subido.',
    constraintKind: 'process',
    plainExplanation: 'Qualidade vira um departamento no fim. Quem constrói descobre o problema quando já comprometeu o desenho. Organizações maduras colocam o risco na definição do item e a verificação no meio do caminho.',
    solutionKind: 'policy',
    solutionClass: 'Risco na definição do item; verificação como feedback durante a construção',
    matureReference: 'Qualidade no fluxo',
    whyItWorks: 'O retrabalho aparece enquanto ainda cabe no lote pequeno.',
    doesNotSolve: 'Não substitui competência de risco que o time ainda não consegue exercer sozinho.',
    examples: 'Critério de pronto com risco nomeado e verificação proporcional — não “mais QA no fim”.',
    antiPattern: 'Contratar mais gente para a fila final sem mudar quando o risco entra na conversa.',
    metric: 'espera na fila final e retrabalho depois do “pronto para qualidade”',
    successCriterion: 'um item pequeno leva risco e verificação durante a construção, com menos devolução no fim',
  },
  'qualidade-como-handoff': {
    mechanism: 'A mudança é entregue a outra função para ser verificada, então contexto e responsabilidade se separam.',
    constraintKind: 'structure',
    plainExplanation: 'Quem testa não estava na decisão e quem decidiu já passou para o próximo item. O handoff cria fila e perda de contexto, não “rigor”.',
    solutionKind: 'org-design',
    solutionClass: 'Qualidade como especialidade no fluxo, não como etapa posterior',
    matureReference: 'Qualidade no fluxo',
    whyItWorks: 'A pessoa que vê o risco ainda consegue alterar o desenho.',
    doesNotSolve: 'Não cria tempo se o portfólio continua sem capacidade para verificação.',
    examples: 'Participação no refinamento e verificação compartilhada — QA habilitador, não portão.',
    antiPattern: 'Renomear o time de QA sem mudar o momento em que ele entra.',
    metric: 'tempo de espera no handoff e retrabalho após a devolução',
    successCriterion: 'a próxima mudança discute risco antes de “passar para qualidade”',
  },
  'qualidade-tardia': {
    mechanism: 'Contexto de risco chega depois da implementação, então a verificação descobre o que a definição deveria ter excluído.',
    constraintKind: 'process',
    plainExplanation: 'Começa-se a construir e só depois se pergunta o que pode dar errado. O atraso não é técnico: é de quando o risco entra na conversa.',
    solutionKind: 'practice',
    solutionClass: 'Definição conjunta de risco antes de implementar o item pequeno',
    matureReference: 'Qualidade no fluxo',
    whyItWorks: 'Menos trabalho é feito no desenho errado.',
    doesNotSolve: 'Não cobre ameaça que só aparece em produção se ninguém observou o uso.',
    examples: 'Um item, um risco nomeado, uma verificação combinada no início.',
    antiPattern: 'Checklist genérico colado depois do código pronto.',
    metric: 'itens reabertos depois da implementação por risco não discutido',
    successCriterion: 'o próximo item pequeno registra risco e evidência esperada antes de começar',
  },
  'espera-normalizada': {
    mechanism: 'Diante do bloqueio, o grupo inicia outro trabalho; a espera some da vista e o fluxo fica cheio de itens parados.',
    constraintKind: 'incentive',
    plainExplanation: 'Ninguém gosta de parecer ocioso. Começar mais uma coisa esconde a fila. O sistema fica ocupado e o resultado demora. A correção é parar de iniciar, não contratar mais gente para o mesmo padrão.',
    solutionKind: 'policy',
    solutionClass: 'Limite de trabalho em andamento: um bloqueio visível para o fluxo, não mais itens',
    matureReference: 'Lean / Accelerate',
    whyItWorks: 'A espera vira problema do sistema e ganha dono, em vez de virar outro começo.',
    doesNotSolve: 'Não remove a dependência externa; só impede que ela seja mascarada.',
    examples: 'Política de WIP e quadro que mostra bloqueio — sem ferramenta de kanban como prova de maturidade.',
    antiPattern: 'Comprar um quadro digital e continuar iniciando item novo a cada espera.',
    metric: 'itens iniciados após bloqueio e tempo até o bloqueio original ser removido',
    successCriterion: 'no próximo bloqueio relevante o grupo não inicia um item novo antes de atacar a espera',
  },
  'ocupacao-como-progresso': {
    mechanism: 'O reconhecimento pesa pessoa ocupada, então o sistema otimiza utilização local e alonga o tempo até valor.',
    constraintKind: 'incentive',
    plainExplanation: 'Se “estar ocupado” é o sinal de progresso, ninguém protege o fluxo. Filas entre etapas crescem enquanto cada um parece produtivo.',
    solutionKind: 'policy',
    solutionClass: 'Medir e reconhecer uma entrega ponta a ponta, incluindo espera',
    matureReference: 'Lean / Accelerate',
    whyItWorks: 'O incentivo deixa de punir quem reduz fila.',
    doesNotSolve: 'Não define sozinho qual resultado de negócio importa.',
    examples: 'Lead time e limite de WIP no ciclo de reconhecimento — não meta de tickets fechados.',
    antiPattern: 'Dashboard de ocupação individual como prova de desempenho.',
    metric: 'tempo ponta a ponta versus utilização local no recorte acompanhado',
    successCriterion: 'a próxima revisão de progresso usa espera e conclusão, não só ocupação',
  },
  'causa-fronteira-times': {
    mechanism: 'O trabalho só termina depois de atravessar grupos que não compartilham resultado, então a coordenação vira o produto.',
    constraintKind: 'structure',
    plainExplanation: 'Ninguém é dono do caminho inteiro. Cada grupo otimiza sua parte e a espera mora na passagem. Isso não se resolve com mais reunião: resolve-se com fronteira e modo de interação explícitos.',
    solutionKind: 'org-design',
    solutionClass: 'Time alinhado ao fluxo ou contrato explícito com a plataforma / subsistema difícil',
    matureReference: 'Team Topologies',
    whyItWorks: 'A decisão e o resultado voltam a caber num grupo que consegue terminar.',
    doesNotSolve: 'Não apaga um acoplamento de código que obriga dois grupos a mudar o mesmo ponto.',
    examples: 'Stream-aligned, plataforma com caminho self-service, ou colaboração temporária nomeada — sem copiar o organograma de um livro.',
    antiPattern: 'Criar um “time de integração” permanente para carregar a passagem.',
    metric: 'passagens recorrentes e espera na fronteira da jornada escolhida',
    successCriterion: 'uma passagem deixa de ser necessária ou ganha dono de resultado ponta a ponta',
  },
  'ownership-fragmentado': {
    mechanism: 'Prioridade e responsabilidade se partem nas fronteiras, então cada etapa tem dono e o resultado não tem.',
    constraintKind: 'structure',
    plainExplanation: 'Várias pessoas “são responsáveis” e ninguém pode terminar. O gestor vê atraso; cada time vê que fez a sua parte.',
    solutionKind: 'org-design',
    solutionClass: 'Um responsável pelo resultado da jornada, com autoridade na passagem',
    matureReference: 'Team Topologies',
    whyItWorks: 'O conflito de prioridade aparece numa decisão, não em várias filas.',
    doesNotSolve: 'Não substitui competência que o grupo ainda não tem no meio da jornada.',
    examples: 'Ownership de serviço ou de jornada — não um cargo novo sem poder de recusar demanda.',
    antiPattern: 'Nomear um “PO de tudo” sem tirar demanda conflitante.',
    metric: 'mudanças transversais com decisão explícita de ponta a ponta',
    successCriterion: 'uma jornada crítica tem quem pode reordenar as etapas em função do resultado',
  },
  'dependencia-de-heroi': {
    mechanism: 'Só uma pessoa consegue diagnosticar; o sistema não deixa o raciocínio reproduzível para quem está de resposta.',
    constraintKind: 'skill',
    plainExplanation: 'O conhecimento mora na cabeça. Na folga ou no turno, o fluxo para. Documentar depois do incidente não basta: o caminho de diagnóstico precisa ser usável por outra pessoa na hora.',
    solutionKind: 'practice',
    solutionClass: 'Diagnóstico reproduzível: hipóteses, consultas e decisão registradas no caminho',
    matureReference: 'SRE / blameless postmortem',
    whyItWorks: 'A próxima ocorrência não espera a mesma pessoa.',
    doesNotSolve: 'Não cria telemetria que simplesmente não existe.',
    examples: 'Runbook vivo e busca correlacionada — classe de prática, não a marca da observabilidade.',
    antiPattern: 'Gravar um vídeo do herói e chamar isso de capacitação.',
    metric: 'eventos em que a mitigação esperou a pessoa concentrada e tempo até outra pessoa repetir o diagnóstico',
    successCriterion: 'uma pessoa que não fez a última correção conclui o próximo diagnóstico equivalente',
  },
  'provisionamento-em-fila': {
    mechanism: 'Ambiente e permissão chegam por pedido a outro grupo, então a espera é estrutural, não um incidente isolado.',
    constraintKind: 'platform',
    plainExplanation: 'Para começar o trabalho, alguém abre um chamado. Isso não é “falta de cloud”: é ausência de um caminho que o próprio time consiga seguir com limite e trilha.',
    solutionKind: 'platform-capability',
    solutionClass: 'Self-service com guardrail para o pedido mais repetido',
    matureReference: 'Well-Architected / platform engineering',
    whyItWorks: 'A espera deixa de ser a fila de outra equipe.',
    doesNotSolve: 'Não autoriza acesso irrestrito; o guardrail é parte da classe.',
    examples: 'Portal ou API de plataforma com política — família de IDP, sem pontuar por ter um portal.',
    antiPattern: 'Criar um time de plataforma que só opera a mesma fila com outro nome.',
    metric: 'tempo do pedido recorrente até o caminho utilizável e proporção ainda na fila artesanal',
    successCriterion: 'o pedido mais repetido tem caminho com tempo observável, sem ticket ao herói',
  },
  'capacidade-nova-por-ticket-heroi': {
    mechanism: 'Usar a capacidade da plataforma depende de ticket ou da pessoa que “conhece o caminho”, então autonomia é teatro.',
    constraintKind: 'platform',
    plainExplanation: 'A documentação existe, mas só funciona com quem escreveu. O time consumidor continua pedindo ajuda. Plataforma madura é o caminho que outra pessoa completa sem o autor.',
    solutionKind: 'platform-capability',
    solutionClass: 'Caminho pavimentado: exemplo, limite e tempo previsível sem o herói',
    matureReference: 'Well-Architected / platform engineering',
    whyItWorks: 'A adoção deixa de ser um favor pessoal.',
    doesNotSolve: 'Não corrige um produto interno que ainda não resolve o caso real do consumidor.',
    examples: 'Golden path com exercício feito por quem não o escreveu.',
    antiPattern: 'Mais páginas de wiki no lugar do passo que trava.',
    metric: 'pedidos ao herói e tempo até um consumidor novo completar o caminho sozinho',
    successCriterion: 'uma pessoa que não escreveu o caminho conclui o pedido recorrente no tempo combinado',
  },
  'documentacao-substitui-caminho': {
    mechanism: 'O texto descreve o procedimento, mas o procedimento não é executável por quem não o escreveu.',
    constraintKind: 'platform',
    plainExplanation: 'Ler não é conseguir fazer. O travamento na primeira tentativa é o sinal; a página extra não remove o herói.',
    solutionKind: 'practice',
    solutionClass: 'Validar o caminho com uma pessoa que não o escreveu e pavimentar o que travar',
    matureReference: 'Well-Architected / platform engineering',
    whyItWorks: 'O próximo passo do produto interno é o obstáculo real, não o índice da wiki.',
    doesNotSolve: 'Não cria a capacidade se a plataforma ainda não oferece a operação.',
    examples: 'Teste de usabilidade do caminho — não um portal como medalha.',
    antiPattern: 'Exigir que o time “leia a documentação” depois de falhar o caminho.',
    metric: 'tentativas em que o consumidor precisou do autor para concluir',
    successCriterion: 'o ponto que travou vira passo suportado na próxima utilização',
  },
  'acesso-artesanal': {
    mechanism: 'Permissão e provisão dependem de coordenação pessoal, então urgência vira quem conhece o aprovador.',
    constraintKind: 'autonomy',
    plainExplanation: 'O acesso certo não tem caminho; tem conversa. Isso concentra risco e espera. A classe é identidade com escopo, validade e trilha — não um cofre comprado no vazio.',
    solutionKind: 'policy',
    solutionClass: 'Acesso mínimo, expiração e trilha no pedido frequente',
    matureReference: 'Well-Architected — Security',
    whyItWorks: 'A urgência deixa de ser um favor e o privilégio deixa de ser permanente por omissão.',
    doesNotSolve: 'Não modela a ameaça se ninguém descreveu o que o acesso permite fazer de errado.',
    examples: 'Identidade de carga ou de pessoa com revogação — classe, não o produto de cofre.',
    antiPattern: 'Comprar o cofre e continuar mandando a senha no chat “só dessa vez”.',
    metric: 'espera por acesso e concessões sem expiração no pedido recorrente',
    successCriterion: 'o pedido frequente ganha caminho com expiração e trilha, sem ampliar privilégio permanente',
  },
  'causa-melhoria-sem-capacidade': {
    mechanism: 'Toda a capacidade vai para entrega visível; o gargalo conhecido não recebe tempo, dono nem revisão de efeito.',
    constraintKind: 'incentive',
    plainExplanation: 'O grupo sabe o que dói e não para nada para atacar. Melhoria vira cartão no fim da fila. Aqui o fundamento é mesmo o ciclo de melhoria: sem capacidade reservada, o aprendizado não muda o sistema.',
    solutionKind: 'policy',
    solutionClass: 'Capacidade reservada e uma iniciativa pequena parada para remover o gargalo',
    matureReference: 'Lean / melhoria contínua',
    whyItWorks: 'O problema deixa de competir só com o discurso; compete com o portfólio.',
    doesNotSolve: 'Não dá autonomia se a causa está fora do poder do grupo.',
    examples: 'WIP de melhoria com data de revisão — não uma retrospectiva extra.',
    antiPattern: 'Abrir mais ações de melhoria sem parar trabalho que consome a capacidade.',
    metric: 'capacidade de fato gasta no gargalo versus novas iniciativas iniciadas',
    successCriterion: 'uma iniciativa pequena para e a espera do gargalo cai no horizonte combinado',
  },
  'retrospectiva-sem-fechamento': {
    mechanism: 'A reflexão produz lista; as ações perdem dono, prazo e critério, então a cerimônia se repete sem efeito.',
    constraintKind: 'process',
    plainExplanation: 'Reunir e anotar não é melhorar. Sem dono e sem “como saber se parou”, a lista vira arquivo. Este é o caso em que o ciclo de melhoria é o mecanismo.',
    solutionKind: 'practice',
    solutionClass: 'Uma mudança, um dono, um sinal, uma data de encerramento',
    matureReference: 'Lean / melhoria contínua',
    whyItWorks: 'O grupo revisa efeito, não volume de post-its.',
    doesNotSolve: 'Não remove uma restrição de autonomia ou de plataforma.',
    examples: 'Limite de ações em aberto — não ferramenta de retro.',
    antiPattern: 'Fazer a cerimônia mais longa para “caber” mais ações.',
    metric: 'ações com efeito revisado versus ações só concluídas no papel',
    successCriterion: 'a próxima reflexão encerra ou revisa uma ação pelo efeito, não só pelo status',
  },
  'feedback-em-producao': {
    mechanism: 'A primeira prova de que as partes não combinam é o usuário; o caminho de mudança não tem verificação conjunta antes da exposição.',
    constraintKind: 'process',
    plainExplanation: 'O cliente vira o ambiente de integração. Isso não se resolve com mais atendimento: resolve-se com uma prova conjunta antes de expor.',
    solutionKind: 'practice',
    solutionClass: 'Verificação da interface crítica antes da liberação, com dono da reação',
    matureReference: 'Continuous Delivery',
    whyItWorks: 'O desacordo aparece sem custo de reputação.',
    doesNotSolve: 'Não substitui observabilidade do que só quebra com volume real.',
    examples: 'Teste de contrato ou ensaio em recorte restrito — classe, não a marca.',
    antiPattern: 'Monitorar reclamação como se fosse a estratégia de qualidade.',
    metric: 'incompatibilidades descobertas por usuário versus antes da exposição',
    successCriterion: 'uma interface crítica ganha prova conjunta e reduz descoberta em produção',
  },
  'empacotamento-manual': {
    mechanism: 'Preparar e transportar a versão depende de passos manuais sujeitos a contexto, então espera e variação moram nesse elo.',
    constraintKind: 'platform',
    plainExplanation: 'Uma pessoa “sabe empacotar”. No dia em que ela não está, ou o passo muda, o fluxo para. Automatizar o passo mais frequente não é maturidade por ferramenta: é tirar variação do caminho.',
    solutionKind: 'tool-class',
    solutionClass: 'Empacotamento repetível a partir de uma origem única',
    matureReference: 'Continuous Delivery',
    whyItWorks: 'A promoção deixa de ser um rito pessoal.',
    doesNotSolve: 'Não define qual versão é a válida se ainda existem caminhos paralelos.',
    examples: 'Família de empacotamento e promoção automatizados.',
    antiPattern: 'Script na máquina do especialista sem origem compartilhada.',
    metric: 'espera e falhas no passo manual mais frequente',
    successCriterion: 'o passo mais repetido deixa de depender do contexto da pessoa que o executava',
  },
  'sobrecarga-silenciosa': {
    mechanism: 'Urgências entram sem tirar trabalho nem registrar o risco aceito, então a capacidade real desaparece da conversa.',
    constraintKind: 'incentive',
    plainExplanation: 'Todo mundo “encaixa mais um”. O sistema finge que a capacidade é elástica. O desgaste e o atraso aparecem depois, como se fossem acidente.',
    solutionKind: 'policy',
    solutionClass: 'Troca visível: o que entra, o que sai, o risco e a data de revisão',
    matureReference: 'Lean / Accelerate',
    whyItWorks: 'A prioridade vira decisão, não absorção.',
    doesNotSolve: 'Não cria autonomia se quem absorve não pode recusar.',
    examples: 'Registro conjunto de troca de prioridade — não um software de tickets como prova.',
    antiPattern: 'Heroísmo celebrado como cultura de dono.',
    metric: 'urgências que não registraram o que saiu e retrabalho ou atraso no que foi preterido',
    successCriterion: 'a próxima urgência torna explícito o que para e quando o efeito será revisto',
  },
  'heroi-troca-contexto': {
    mechanism: 'O fluxo depende de quem troca de contexto mais rápido, então a carga cognitiva de uma pessoa vira a capacidade do grupo.',
    constraintKind: 'structure',
    plainExplanation: 'A mesma pessoa apaga incêndio, tira dúvida e empurra a entrega. Isso parece eficiência e é fragilidade: o limite é o cérebro dela.',
    solutionKind: 'org-design',
    solutionClass: 'Separar um tipo de trabalho recorrente num modo de colaboração explícito',
    matureReference: 'Team Topologies',
    whyItWorks: 'A semana deixa de depender da pessoa que mais troca de contexto.',
    doesNotSolve: 'Não treina a competência se ela simplesmente não existe no grupo.',
    examples: 'Enabling temporário ou plataforma para o tipo de pedido — não um cargo de herói oficial.',
    antiPattern: 'Premiar a pessoa que mais troca de contexto.',
    metric: 'interrupções na mesma pessoa e espera quando ela não está',
    successCriterion: 'um tipo de pedido deixa de passar pela mesma pessoa na semana observada',
  },
  'causa-verificacao-concorrente': {
    mechanism: 'Mudanças concorrentes não têm prova antecipada de contrato ou composição, então o conflito só aparece na junta final.',
    constraintKind: 'process',
    plainExplanation: 'Dois grupos alteram o mesmo acordo sem um alarme cedo. Planejar mais não substitui uma verificação reproduzível da superfície compartilhada.',
    solutionKind: 'practice',
    solutionClass: 'Verificação de contrato ou composição antes da liberação conjunta',
    matureReference: 'Continuous Delivery',
    whyItWorks: 'O desacordo aparece enquanto cada mudança ainda é pequena.',
    doesNotSolve: 'Não realinha ownership se os dois grupos não compartilham o resultado.',
    examples: 'Teste de contrato, schema ou configuração compartilhada — classe de verificação.',
    antiPattern: 'Mais reunião de alinhamento sem a prova automática.',
    metric: 'conflitos descobertos só na junta e espera para reconciliar a superfície',
    successCriterion: 'a verificação antecipa o último conflito da mesma classe',
  },
  'solucao-entregue-pronta': {
    mechanism: 'A solução é fechada antes de negócio, produto e competências técnicas compararem opções, então restrições e hipóteses só conseguem alterar a execução, não a decisão.',
    constraintKind: 'process', plainExplanation: 'A implementação recebe uma resposta pronta. Quando risco, viabilidade ou evidência aparecem, voltar atrás já custa mais.',
    solutionKind: 'practice', solutionClass: 'Comparação multidisciplinar de opções antes de fechar o desenho', matureReference: 'Discovery e evidência de uso',
    whyItWorks: 'As competências necessárias ainda conseguem alterar escopo e abordagem.', doesNotSolve: 'Não cria autonomia quando a solução vem como ordem não contestável.',
    examples: 'Hipótese, alternativas e restrições numa mudança real — não cerimônia adicional.', antiPattern: 'Chamar refinamento depois que solução e prazo já estão fechados.',
    metric: 'decisões de desenho alteradas antes da implementação e retrabalho descoberto depois do início', successCriterion: 'a próxima solução relevante compara opções e registra ao menos uma decisão alterada por evidência ou restrição',
  },
  'correcao-direta-na-producao': {
    mechanism: 'A correção emergencial altera o ambiente sem reconciliar a fonte declarativa, criando dois caminhos capazes de definir o estado real.',
    constraintKind: 'platform', plainExplanation: 'A urgência termina no ambiente, mas a fonte continua contando outra história. A próxima mudança pode desfazer a correção ou reproduzir a divergência.',
    solutionKind: 'platform-capability', solutionClass: 'Reconciliação automática e detecção de divergência', matureReference: 'Infrastructure as Code / SRE',
    whyItWorks: 'O caminho emergencial preserva uma única origem reproduzível.', doesNotSolve: 'Não elimina a necessidade de acesso emergencial proporcional.',
    examples: 'Reconciliar alteração na fonte e alertar drift — não apenas bloquear o console.', antiPattern: 'Retirar acesso antes de existir um caminho emergencial seguro.',
    metric: 'alterações emergenciais não reconciliadas e tempo até a fonte voltar a representar o ambiente', successCriterion: 'a próxima correção emergencial é reconciliada na fonte e não deixa divergência detectável',
  },
  'contorno-acumula-divida': {
    mechanism: 'O contorno reduz a espera local sem validade nem condição de remoção, então o custo é transferido para reconciliações futuras.',
    constraintKind: 'structure', plainExplanation: 'O trabalho anda agora, mas cria uma segunda forma de operar que permanece sem dono.',
    solutionKind: 'policy', solutionClass: 'Contorno temporário com validade, responsável e reconciliação', matureReference: 'Lean / arquitetura evolutiva',
    whyItWorks: 'A exceção deixa explícito quando e como voltará ao caminho comum.', doesNotSolve: 'Não remove sozinho a dependência que provocou a espera.',
    examples: 'Prazo e condição de retirada ligados ao mesmo fluxo.', antiPattern: 'Registrar dívida sem reservar a reconciliação.',
    metric: 'contornos ativos após a validade e tempo gasto em reconciliações posteriores', successCriterion: 'o próximo contorno tem responsável, validade e é removido ou reconciliado no prazo definido',
  },
  'concorrencia-coordenada-manualmente': {
    mechanism: 'Mudanças concorrentes dependem de alinhamentos recorrentes porque a superfície compartilhada não oferece uma verificação antecipada de composição ou contrato.',
    constraintKind: 'architecture', plainExplanation: 'As pessoas evitam colisão conversando o tempo todo. O acordo não é verificável quando uma das partes muda.',
    solutionKind: 'practice', solutionClass: 'Verificação antecipada da superfície compartilhada', matureReference: 'Continuous Delivery / arquitetura evolutiva',
    whyItWorks: 'O conflito aparece na mudança, antes da janela coordenada.', doesNotSolve: 'Não resolve ownership incompatível com o fluxo de valor.',
    examples: 'Contrato, schema ou composição verificável.', antiPattern: 'Adicionar reunião sem criar uma prova reproduzível.',
    metric: 'alinhamentos necessários por mudança e conflitos descobertos apenas na composição final', successCriterion: 'a próxima mudança concorrente detecta o conflito pela verificação antes da coordenação final',
  },
  'credencial-em-configuracao': {
    mechanism: 'A entrega transporta uma credencial porque não há um caminho de identidade com escopo, validade e injeção controlada no ambiente.',
    constraintKind: 'platform', plainExplanation: 'O segredo acompanha a configuração para o trabalho andar e pode permanecer legível, reutilizável ou difícil de revogar.',
    solutionKind: 'platform-capability', solutionClass: 'Identidade de workload ou injeção de credencial curta e rastreável', matureReference: 'Well-Architected — Security',
    whyItWorks: 'O artefato deixa de carregar o segredo e o acesso passa a ter escopo e ciclo de vida.', doesNotSolve: 'Não define privilégios corretos sem ownership do serviço.',
    examples: 'Credencial curta injetada no runtime — a classe, não uma marca de cofre.', antiPattern: 'Mover a senha para outro arquivo permanente.',
    metric: 'artefatos com segredo, acessos permanentes e tempo necessário para revogação', successCriterion: 'a próxima mudança autentica sem transportar segredo no artefato e permite revogação sem reconstruí-lo',
  },
  'seguranca-depende-de-reconhecimento-e-especialista': {
    mechanism: 'O risco só altera a mudança quando alguém o reconhece e consegue envolver um especialista, portanto o feedback depende de memória e disponibilidade.',
    constraintKind: 'skill', plainExplanation: 'Sem a pessoa certa, a mudança pode avançar sem que o risco seja percebido ou tratado no desenho.',
    solutionKind: 'practice', solutionClass: 'Orientação, verificação e consulta de segurança acessíveis no fluxo', matureReference: 'Security by design / qualidade no fluxo',
    whyItWorks: 'Riscos recorrentes recebem feedback enquanto ainda é possível alterar a construção.', doesNotSolve: 'Não automatiza riscos que exigem julgamento contextual.',
    examples: 'Guardrail para classe recorrente e consulta explícita para exceções.', antiPattern: 'Transformar todo risco em checklist ou portão final.',
    metric: 'tempo até feedback de segurança, mudanças devolvidas tarde e exceções que aguardam especialista', successCriterion: 'a próxima ocorrência recorrente recebe orientação no fluxo e envolve especialista apenas pelo critério de exceção',
  },
  'prestigio-tecnico': {
    mechanism: 'A escolha se sustenta pela autoridade de quem propõe, sem tornar problema, restrições e alternativa mais simples comparáveis.',
    constraintKind: 'architecture', plainExplanation: 'O desenho parece decidido pela reputação da solução ou da pessoa. O grupo não consegue revisar a escolha quando o contexto muda.',
    solutionKind: 'practice', solutionClass: 'Decisão arquitetural comparável e reversível', matureReference: 'Arquitetura evolutiva',
    whyItWorks: 'Problema, trade-offs e sinais de revisão ficam independentes da autoridade pessoal.', doesNotSolve: 'Não cria competência técnica onde ela não existe.',
    examples: 'Comparar alternativa simples no contexto da mudança.', antiPattern: 'Criar documento para justificar uma escolha já encerrada.',
    metric: 'decisões com alternativas explícitas e revisões disparadas pelos sinais definidos', successCriterion: 'a próxima escolha relevante compara uma alternativa mais simples e registra o sinal que faria revisá-la',
  },
  'mudanca-emergencial-reconciliada': {
    mechanism: 'A exceção é reconciliada depois, mas ainda depende de trabalho manual e memória para restaurar fonte, validações e auditoria.',
    constraintKind: 'platform', plainExplanation: 'O grupo fecha a emergência corretamente, porém paga novamente o custo de reconstruir o caminho seguro após cada evento.',
    solutionKind: 'platform-capability', solutionClass: 'Caminho emergencial exercitado com reconciliação automática', matureReference: 'SRE / Infrastructure as Code',
    whyItWorks: 'A urgência preserva a origem reproduzível sem depender de uma etapa posterior esquecível.', doesNotSolve: 'Não torna toda mudança emergencial justificável.',
    examples: 'Exercício controlado de correção e reconciliação.', antiPattern: 'Automatizar acesso amplo sem limites e auditoria.',
    metric: 'tempo e passos manuais entre a correção emergencial e a reconciliação verificável', successCriterion: 'o próximo exercício conclui correção e reconciliação pelo mesmo caminho auditável, sem etapa manual posterior',
  },
  'incentivo-segue-entrega': {
    mechanism: 'O reconhecimento premia volume entregue ou heroísmo sem verificar o efeito e o risco deslocado, então o sistema reforça iniciar e apagar incêndios.',
    constraintKind: 'incentive', plainExplanation: 'As pessoas aprendem pelo que é reconhecido. Quando esforço visível vale mais que resultado sustentável, o comportamento frágil se repete.',
    solutionKind: 'policy', solutionClass: 'Reconhecimento ligado a efeito, colaboração e risco explícito', matureReference: 'Lean / Accelerate',
    whyItWorks: 'O incentivo deixa de premiar trabalho iniciado e risco oculto.', doesNotSolve: 'Não corrige uma dependência estrutural sem autoridade para mudá-la.',
    examples: 'Revisar um caso concreto de reconhecimento pelo efeito produzido.', antiPattern: 'Trocar apenas o texto dos valores corporativos.',
    metric: 'decisões de reconhecimento que citam efeito observado e diferença entre trabalho iniciado e resultado alcançado', successCriterion: 'o próximo ciclo de reconhecimento usa evidência de efeito sem premiar volume, heroísmo ou risco oculto',
  },
  'portfolio-sem-feedback': {
    mechanism: 'O investimento continua por plano e consumo de capacidade sem uma evidência de resultado capaz de reduzir, interromper ou redirecionar o trabalho.',
    constraintKind: 'incentive', plainExplanation: 'Entregar o combinado encerra a conversa mesmo quando ainda não sabemos se o resultado apareceu.',
    solutionKind: 'policy', solutionClass: 'Revisão de portfólio orientada por evidência de resultado', matureReference: 'Lean / gestão de produto',
    whyItWorks: 'Continuidade e capacidade voltam a ser decisões condicionadas ao efeito.', doesNotSolve: 'Não cria uma métrica útil quando o resultado ainda não foi definido.',
    examples: 'Revisar uma iniciativa com hipótese, efeito e opção explícita de parar.', antiPattern: 'Adicionar métricas sem permitir que mudem o investimento.',
    metric: 'iniciativas cuja continuidade mudou por evidência e capacidade liberada por trabalho interrompido', successCriterion: 'a próxima revisão altera continuidade, escopo ou capacidade a partir de evidência do resultado',
  },
  'causa-funding-temporario': {
    mechanism: 'Orçamento e pessoas são autorizados para concluir uma iniciativa temporária. Quando a entrega termina, a capacidade se desfaz antes que a evidência possa orientar continuidade ou correção.',
    constraintKind: 'governance', plainExplanation: 'O dinheiro paga a entrega, mas não preserva quem precisa observar o resultado e agir depois.',
    solutionKind: 'policy', solutionClass: 'Financiamento contínuo do resultado com revisão de continuidade', matureReference: 'Lean Product Development / gestão de produto',
    whyItWorks: 'A capacidade permanece ligada ao resultado e pode crescer, mudar ou ser liberada conforme a evidência.', doesNotSolve: 'Não define sozinho um resultado útil nem corrige ownership fragmentado.',
    examples: 'Revisar capacidade de um produto por resultado, sem renovar automaticamente um projeto.', antiPattern: 'Renomear projeto como produto mantendo orçamento, prazo e dissolução do grupo.',
    metric: 'produtos cuja capacidade mudou após revisão de resultado e tempo entre evidência e decisão de investimento', successCriterion: 'a próxima revisão mantém, redireciona ou libera capacidade com base no resultado observado',
  },
  'causa-responsabilidade-encerra-no-aceite': {
    mechanism: 'O aceite encerra a responsabilidade compartilhada; depois dele, resultado, operação e correção passam a grupos diferentes sem autoridade ponta a ponta.',
    constraintKind: 'organization', plainExplanation: 'A entrega tem dono até ficar pronta, mas o efeito que ela produz fica sem um grupo responsável por agir.',
    solutionKind: 'org-design', solutionClass: 'Ownership durável do produto depois da entrega', matureReference: 'Team Topologies / modelo operacional de produto',
    whyItWorks: 'O mesmo grupo preserva contexto e autoridade para observar, corrigir e evoluir o resultado.', doesNotSolve: 'Não cria capacidade se todas as pessoas já estiverem comprometidas com outras iniciativas.',
    examples: 'Responsabilidade conjunta de negócio e tecnologia até a revisão de efeito.', antiPattern: 'Criar um responsável nominal sem capacidade nem poder de decisão.',
    metric: 'resultados sem responsável ativo e tempo entre evidência ruim e ação do grupo responsável', successCriterion: 'uma entrega relevante conserva responsável, capacidade e decisão até a revisão do resultado',
  },
  'causa-capacidade-tomada-pela-proxima-iniciativa': {
    mechanism: 'Novos compromissos ocupam toda a capacidade antes da revisão do trabalho anterior, portanto aprender exige atrasar algo que já foi prometido.',
    constraintKind: 'priority', plainExplanation: 'A equipe sabe que deveria revisar o resultado, mas já recebeu trabalho novo para preencher todo o tempo disponível.',
    solutionKind: 'policy', solutionClass: 'Capacidade condicionada à revisão de resultado', matureReference: 'Lean portfolio management',
    whyItWorks: 'A revisão passa a disputar capacidade antes dos novos compromissos, quando ainda é possível mudar a decisão.', doesNotSolve: 'Não ajuda se a evidência de resultado não existe ou não é confiável.',
    examples: 'Reservar capacidade antes de autorizar todo o próximo ciclo de investimento.', antiPattern: 'Adicionar uma reunião de métricas sem liberar capacidade para agir.',
    metric: 'resultados revistos antes do próximo compromisso e capacidade alterada pela revisão', successCriterion: 'a próxima iniciativa começa preservando capacidade para uma decisão baseada no resultado anterior',
  },
  'causa-resultado-sem-autoridade': {
    mechanism: 'Prazo e escopo determinam reconhecimento e prestação de contas; a evidência de resultado é informativa, mas não pode mudar continuidade, prioridade ou capacidade.',
    constraintKind: 'incentive', plainExplanation: 'As pessoas são cobradas por terminar o combinado. Mesmo quando o resultado decepciona, parar ou mudar parece fracasso.',
    solutionKind: 'policy', solutionClass: 'Direito explícito de mudar ou encerrar investimento', matureReference: 'Evidence-Based Management / Lean Product Development',
    whyItWorks: 'Aprender e interromper trabalho sem efeito passam a ser decisões legítimas, não desvios do plano.', doesNotSolve: 'Não substitui uma hipótese clara nem evidência confiável de resultado.',
    examples: 'Revisão com opções reais de continuar, redirecionar ou encerrar.', antiPattern: 'Celebrar aprendizado mantendo todos os compromissos intactos.',
    metric: 'revisões que mudaram continuidade, prioridade ou capacidade e trabalho encerrado por evidência', successCriterion: 'a próxima revisão altera uma decisão material quando o resultado contradiz o plano',
  },
  'caminho-desconhecido': {
    mechanism: 'A capacidade foi publicada fora dos lugares e momentos em que o time procura resolver a necessidade, por isso sua descoberta depende de relações pessoais.',
    constraintKind: 'skill', plainExplanation: 'O caminho existe, mas só é encontrado quando alguém indica a pessoa ou o endereço certo.',
    solutionKind: 'platform-capability', solutionClass: 'Descoberta contextual do caminho suportado', matureReference: 'Platform as a Product',
    whyItWorks: 'A necessidade comum conduz ao caminho antes que o time crie uma alternativa.', doesNotSolve: 'Não melhora um caminho conhecido que continua inadequado ou bloqueado.',
    examples: 'Entrada pesquisável pela tarefa e ligada ao fluxo já usado pelo time.', antiPattern: 'Criar outro portal sem observar onde as pessoas procuram ajuda.',
    metric: 'tempo até encontrar o caminho e pedidos que começam por indicação pessoal', successCriterion: 'uma pessoa que não conhecia a capacidade encontra o caminho a partir da necessidade sem indicação individual',
  },
  'caminho-conhecido-inacessivel': {
    mechanism: 'Permissão ou critério de entrada trata o caso comum como exceção e exige intervenção externa antes da primeira execução.',
    constraintKind: 'autonomy', plainExplanation: 'O time sabe o que fazer, mas precisa esperar alguém liberar ou executar o primeiro passo.',
    solutionKind: 'policy', solutionClass: 'Entrada proporcional ao risco com escopo e trilha', matureReference: 'Well-Architected — Security',
    whyItWorks: 'O caso comum começa sem favor pessoal e o risco permanece verificável.', doesNotSolve: 'Não torna o caminho adequado nem concede acesso irrestrito.',
    examples: 'Acesso mínimo, temporário e auditável para uma operação frequente.', antiPattern: 'Remover toda aprovação sem nomear o risco protegido.',
    metric: 'espera antes da primeira execução e liberações manuais para casos comuns', successCriterion: 'o próximo caso comum começa pelo caminho com acesso mínimo e trilha, sem liberação pessoal',
  },
  'caminho-inadequado-ao-caso': {
    mechanism: 'O caminho foi desenhado para um caso diferente e omite uma restrição recorrente dos consumidores, que mantêm solução própria para concluir o trabalho.',
    constraintKind: 'platform', plainExplanation: 'O time conhece e acessa o caminho, mas ele não resolve uma necessidade que aparece com frequência.',
    solutionKind: 'platform-capability', solutionClass: 'Evolução do caminho pela necessidade recorrente do consumidor', matureReference: 'Platform as a Product',
    whyItWorks: 'A plataforma incorpora a menor lacuna repetida e reduz contornos sem absorver toda exceção.', doesNotSolve: 'Não justifica padronizar uma necessidade única ou local.',
    examples: 'Testar a ampliação com um consumidor e uma restrição concreta.', antiPattern: 'Culpar adoção ou obrigar migração sem testar adequação.',
    metric: 'contornos motivados pela mesma restrição e esforço para concluir o caso pelo caminho', successCriterion: 'o próximo caso equivalente conclui pelo caminho comum sem manter a solução paralela',
  },
  'caminho-depende-de-ajuda-recorrente': {
    mechanism: 'O feedback do caminho não permite que o consumidor recupere sozinho uma falha comum, então suporte humano completa repetidamente a operação.',
    constraintKind: 'skill', plainExplanation: 'O caminho funciona, mas sempre trava no mesmo ponto e alguém da plataforma precisa destravar.',
    solutionKind: 'platform-capability', solutionClass: 'Feedback recuperável no ponto recorrente de ajuda', matureReference: 'Platform as a Product / DevEx',
    whyItWorks: 'A orientação aparece durante a execução e reduz dependência sem transferir toda a complexidade.', doesNotSolve: 'Não corrige falta de acesso nem inadequação estrutural do caminho.',
    examples: 'Erro acionável, validação antecipada ou padrão seguro no ponto frequente.', antiPattern: 'Produzir mais documentação geral sem observar a tentativa.',
    metric: 'pedidos repetidos de ajuda por etapa e conclusão sem intervenção especializada', successCriterion: 'uma pessoa nova recupera o erro mais frequente e conclui sem mensagem ou execução externa',
  },
  'caminhos-equivalentes-fragmentados': {
    mechanism: 'Grupos mantêm soluções sobrepostas sem diferença explícita de necessidade, multiplicando escolha, integração e manutenção para consumidores.',
    constraintKind: 'platform', plainExplanation: 'Há várias formas de fazer quase a mesma coisa, e o time precisa escolher por familiaridade ou combinar pedaços.',
    solutionKind: 'platform-capability', solutionClass: 'Consolidação orientada por necessidades distintas', matureReference: 'Platform as a Product / Team Topologies',
    whyItWorks: 'A escolha permanece somente quando atende uma restrição diferente e observável.', doesNotSolve: 'Não obriga uma única tecnologia quando contextos realmente diferem.',
    examples: 'Comparar dois caminhos pela necessidade, adoção e custo de manutenção.', antiPattern: 'Escolher vencedor por preferência técnica e migrar todos de uma vez.',
    metric: 'caminhos equivalentes por necessidade e times que combinam alternativas', successCriterion: 'uma sobreposição sem necessidade distinta é retirada com consumidores migrados e suporte preservado',
  },
  'adocao-do-caminho-nao-observada': {
    mechanism: 'A plataforma mede publicação e conclusão de pedidos, mas não a jornada entre descoberta, tentativa, ajuda, abandono e contorno.',
    constraintKind: 'platform', plainExplanation: 'A capacidade aparece como entregue mesmo quando não sabemos se os times conseguem ou preferem usá-la.',
    solutionKind: 'practice', solutionClass: 'Observação ponta a ponta da adoção do produto interno', matureReference: 'Platform as a Product',
    whyItWorks: 'A decisão passa a enxergar fricção e alternativas antes invisíveis.', doesNotSolve: 'Não prova que baixa adoção é culpa da plataforma sem investigar o contexto.',
    examples: 'Acompanhar uma necessidade desde busca até conclusão ou abandono.', antiPattern: 'Usar acesso ao portal ou quantidade de templates como adoção.',
    metric: 'conclusão, abandono, ajuda e contorno por jornada comum', successCriterion: 'a próxima revisão do caminho usa ao menos uma evidência de tentativa ou abandono para mudar a decisão',
  },
  'suporte-substitui-feedback-de-produto-interno': {
    mechanism: 'O roadmap usa somente chamados, portanto consumidores silenciosos, contornos e abandonos não participam da priorização.',
    constraintKind: 'process', plainExplanation: 'A plataforma escuta quem pede ajuda, mas não quem desistiu ou resolveu por fora.',
    solutionKind: 'practice', solutionClass: 'Discovery contínuo com consumidores do caminho', matureReference: 'Platform as a Product',
    whyItWorks: 'Necessidade, fricção e efeito entram na decisão além do volume da fila.', doesNotSolve: 'Não substitui suporte operacional nem promete atender toda preferência.',
    examples: 'Comparar pessoas que concluíram, pediram ajuda e contornaram.', antiPattern: 'Tratar o chamado mais frequente como votação automática de roadmap.',
    metric: 'decisões influenciadas por abandono ou contorno e ajuda necessária após a mudança', successCriterion: 'uma mudança testada com consumidores reduz ajuda ou contorno na próxima necessidade equivalente',
  },
  'excecoes-nao-retornam-ao-caminho': {
    mechanism: 'Exceções ficam sem validade e sem retorno para quem mantém a plataforma, transformando necessidades locais em alternativas permanentes e invisíveis.',
    constraintKind: 'structure', plainExplanation: 'Cada time resolve por fora e a plataforma só descobre quando o custo ou o risco já apareceu.',
    solutionKind: 'policy', solutionClass: 'Exceção com validade, responsável e decisão de incorporação', matureReference: 'Platform as a Product / arquitetura evolutiva',
    whyItWorks: 'O desvio deixa de ser invisível e gera decisão explícita de incorporar ou retirar.', doesNotSolve: 'Não torna toda exceção parte do caminho comum.',
    examples: 'Registro leve ligado ao uso, com data e revisão conjunta.', antiPattern: 'Criar comitê de exceção sem prazo nem capacidade de reconciliação.',
    metric: 'exceções ativas após validade e exceções recorrentes desconhecidas pela plataforma', successCriterion: 'a próxima exceção recorrente é incorporada ou retirada na revisão definida',
  },
  'excecao-controlada-com-retorno': {
    mechanism: 'O caminho já permite desvio legítimo com dono, validade e retorno, mas precisa aprender quais exceções devem alterar o padrão.',
    constraintKind: 'platform', plainExplanation: 'A exceção não vira um caminho escondido; ainda é necessário verificar se ela se repete e merece entrar no padrão.',
    solutionKind: 'practice', solutionClass: 'Aprendizado sistemático a partir do escape hatch', matureReference: 'Platform as a Product',
    whyItWorks: 'O padrão evolui sem bloquear necessidades legítimas nem acumular alternativas.', doesNotSolve: 'Não elimina riscos que exigem tratamento excepcional permanente.',
    examples: 'Revisar recorrência e efeito ao encerrar a validade.', antiPattern: 'Celebrar controle da exceção sem revisar seu aprendizado.',
    metric: 'exceções encerradas no prazo e decisões de incorporar ou retirar', successCriterion: 'a próxima exceção termina no prazo e produz uma decisão explícita sobre o caminho comum',
  },
  'governanca-compensa-feedback-tecnico': {
    mechanism: 'A aprovação reconstrói manualmente evidências que testes, esteira ou trilha da mudança ainda não produzem com confiança suficiente.',
    constraintKind: 'platform', plainExplanation: 'O aprovador existe porque o caminho técnico ainda não consegue mostrar sozinho que a mudança é segura.',
    solutionKind: 'platform-capability', solutionClass: 'Evidência técnica confiável consumida pelo controle', matureReference: 'Continuous Delivery / governança habilitadora',
    whyItWorks: 'A decisão recebe a mesma proteção mais cedo e de forma repetível.', doesNotSolve: 'Não autoriza retirar julgamento humano quando o risco é contextual.',
    examples: 'Produzir no fluxo a evidência hoje reconstruída pelo aprovador.', antiPattern: 'Remover aprovação apenas para acelerar ou automatizar um controle sem confiança.',
    metric: 'evidências refeitas na aprovação e espera até a decisão', successCriterion: 'uma mudança de baixo risco chega à decisão com a evidência confiável sem reconstrução manual',
  },
  'governanca-compensa-ownership': {
    mechanism: 'A aprovação reúne várias áreas para compensar a ausência de uma pessoa ou grupo com autoridade e responsabilidade pelo resultado depois da liberação.',
    constraintKind: 'structure', plainExplanation: 'Muita gente aprova porque ninguém consegue decidir e responder pelo risco ponta a ponta.',
    solutionKind: 'org-design', solutionClass: 'Ownership do resultado com autoridade e limites explícitos', matureReference: 'Team Topologies / governança habilitadora',
    whyItWorks: 'A decisão deixa de depender de consenso entre responsáveis parciais.', doesNotSolve: 'Não remove obrigação de revisão independente quando ela é legítima.',
    examples: 'Dono do serviço ou dado com guardrails e caminho de escalada.', antiPattern: 'Nomear owner sem capacidade, informação ou responsabilidade posterior.',
    metric: 'grupos necessários por decisão e decisões reabertas por responsabilidade ambígua', successCriterion: 'a próxima decisão comum possui responsável pelo resultado e dispensa uma passagem criada apenas para reunir donos parciais',
  },
  'segregacao-por-fila-manual': {
    mechanism: 'A política separa solicitação e execução, mas implementa a independência por uma fila humana que repete manualmente uma operação comum.',
    constraintKind: 'autonomy', plainExplanation: 'Separar responsabilidades pode ser correto; obrigar outro grupo a clicar ou copiar toda vez é a parte que gera espera.',
    solutionKind: 'platform-capability', solutionClass: 'Execução limitada e auditável com autorização independente', matureReference: 'Well-Architected — Security',
    whyItWorks: 'A autorização continua separada enquanto a execução ganha repetibilidade e trilha.', doesNotSolve: 'Não elimina segregação exigida nem libera privilégio permanente.',
    examples: 'Solicitante inicia operação predefinida; autorização independente libera execução automática.', antiPattern: 'Dar acesso amplo ao solicitante para eliminar a fila.',
    metric: 'espera entre autorização e execução e operações manuais repetidas', successCriterion: 'a próxima operação comum preserva autorização independente e executa sem ação artesanal do segundo grupo',
  },
  'aprovacao-sem-evidencia-decisoria': {
    mechanism: 'A etapa registra aceite e presença dos responsáveis, mas nenhuma evidência observada altera a decisão, o desenho ou a proteção aplicada.',
    constraintKind: 'governance', plainExplanation: 'A reunião deixa um registro, porém o resultado costuma ser aprovar do mesmo jeito.',
    solutionKind: 'policy', solutionClass: 'Controle com evidência e decisões possíveis explícitas', matureReference: 'Governança habilitadora',
    whyItWorks: 'A etapa permanece somente quando consegue proteger, mudar ou interromper algo.', doesNotSolve: 'Não prova que o risco inexiste nem dispensa obrigação documental.',
    examples: 'Definir evidência mínima e ações possíveis antes da revisão.', antiPattern: 'Trocar reunião por formulário mantendo aprovação automática.',
    metric: 'decisões alteradas pela evidência e espera de etapas sem mudança possível', successCriterion: 'a próxima revisão demonstra qual evidência manteve, alterou ou interrompeu a mudança',
  },
  'compliance-substitui-eficacia': {
    mechanism: 'A manutenção do controle usa presença de registros e aprovação de auditoria como substitutos de evidência sobre risco residual, falhas e custo no fluxo.',
    constraintKind: 'governance', plainExplanation: 'A obrigação foi atendida, mas isso não responde se a etapa realmente evita o problema que deveria evitar.',
    solutionKind: 'practice', solutionClass: 'Revisão conjunta de conformidade, eficácia e custo do controle', matureReference: 'Governança habilitadora / gestão de risco',
    whyItWorks: 'Preserva a obrigação enquanto permite redesenhar uma proteção ineficaz ou desproporcional.', doesNotSolve: 'Não autoriza descumprir requisito externo.',
    examples: 'Comparar evidência exigida, falhas, exceções e espera do controle.', antiPattern: 'Eliminar evidência de auditoria porque a etapa parece lenta.',
    metric: 'falhas apesar do controle, risco residual e espera associada', successCriterion: 'a próxima revisão mantém a obrigação e altera ao menos uma proteção sem efeito ou custo proporcional',
  },
  'excecao-de-risco-renovada-sem-evidencia': {
    mechanism: 'O aceite temporário vence sem produzir evidência nova nem reservar capacidade para reduzir o risco, então a renovação vira o caminho normal.',
    constraintKind: 'priority', plainExplanation: 'A exceção tem prazo, mas nada muda antes dele; quando vence, o mesmo risco é aceito novamente.',
    solutionKind: 'policy', solutionClass: 'Renovação condicionada a evidência e decisão material', matureReference: 'Gestão de risco / governança habilitadora',
    whyItWorks: 'Cada ciclo reduz incerteza ou força uma escolha explícita sobre correção e proteção.', doesNotSolve: 'Não cria capacidade técnica para corrigir o risco.',
    examples: 'Exigir evidência nova, responsável e decisão de proteger, corrigir ou encerrar.', antiPattern: 'Encurtar validade sem reservar capacidade ou mudar evidência.',
    metric: 'renovações consecutivas sem evidência nova e idade do risco aceito', successCriterion: 'a próxima revisão produz evidência nova e muda proteção, prioridade ou continuidade',
  },
  'incidente-apenas-adiciona-controle': {
    mechanism: 'A resposta à falha adiciona uma nova etapa visível sem testar a causa nem retirar proteções antigas, acumulando espera e responsabilidade difusa.',
    constraintKind: 'structure', plainExplanation: 'Cada problema cria mais uma conferência. Com o tempo, ninguém sabe qual etapa ainda evita qual risco.',
    solutionKind: 'practice', solutionClass: 'Revisão sistêmica com substituição explícita de controles', matureReference: 'SRE / blameless postmortem',
    whyItWorks: 'A nova proteção precisa demonstrar a condição tratada e o que torna redundante.', doesNotSolve: 'Não recomenda retirar controle ainda necessário apenas para reduzir tempo.',
    examples: 'Ligar ação à condição da falha e revisar um controle sobreposto.', antiPattern: 'Adicionar sign-off e treinamento como resposta padrão a qualquer falha.',
    metric: 'controles adicionados versus retirados e recorrência da condição tratada', successCriterion: 'a próxima resposta adiciona ou altera uma proteção e retira uma etapa redundante com sinal de risco preservado',
  },
  'competencia-inexistente': {
    mechanism: 'A organização ainda não possui experiência prática suficiente para julgar e executar a decisão, portanto aprende por tentativa ou transfere todo o risco para fora.',
    constraintKind: 'skill', plainExplanation: 'Não há uma pessoa interna que já tenha feito esse trabalho com segurança.',
    solutionKind: 'org-design', solutionClass: 'Aquisição temporária com transferência aplicada de capacidade', matureReference: 'Aprendizagem aplicada / enabling team',
    whyItWorks: 'Especialista reduz o risco inicial enquanto pessoas internas executam um caso menor e repetível.', doesNotSolve: 'Não recomenda contratar permanentemente antes de conhecer recorrência e urgência.',
    examples: 'Especialista acompanha uma entrega reduzida conduzida pelo time.', antiPattern: 'Terceirizar toda execução ou oferecer curso sem caso real.',
    metric: 'decisões ainda dependentes de fonte externa e pessoas internas que repetem o caso', successCriterion: 'uma segunda pessoa interna conclui o próximo caso reduzido com revisão, sem transferir toda execução',
  },
  'competencia-concentrada': {
    mechanism: 'Prazo e risco direcionam repetidamente o trabalho às poucas pessoas experientes, impedindo que colaboração se transforme em execução distribuída.',
    constraintKind: 'structure', plainExplanation: 'O conhecimento existe, mas o trabalho sempre volta para as mesmas pessoas.',
    solutionKind: 'org-design', solutionClass: 'Colaboração temporária com transferência de decisão e execução', matureReference: 'Team Topologies / prática deliberada',
    whyItWorks: 'Outra pessoa assume uma parte verificável com apoio sem devolver todo o caso.', doesNotSolve: 'Não cria conhecimento que ninguém possui.',
    examples: 'Pareamento, rotação ou revisão em uma mudança real pequena.', antiPattern: 'Pedir documentação extra mantendo todo trabalho crítico com o especialista.',
    metric: 'trabalho crítico por pessoa e casos concluídos sem a referência', successCriterion: 'outra pessoa conduz a próxima mudança equivalente com apoio limitado e verificações reproduzíveis',
  },
  'competencia-bloqueada-por-acesso': {
    mechanism: 'Pessoas possuem entendimento suficiente, mas política, privilégio ou fronteira de responsabilidade impede qualquer prática segura no ambiente real.',
    constraintKind: 'autonomy', plainExplanation: 'A pessoa sabe como fazer, porém não pode praticar nem sob acompanhamento.',
    solutionKind: 'policy', solutionClass: 'Prática supervisionada com acesso mínimo, temporário e auditável', matureReference: 'Well-Architected — Security',
    whyItWorks: 'A política preserva o risco enquanto permite demonstrar capacidade operacional.', doesNotSolve: 'Não amplia acesso permanente nem substitui competência ausente.',
    examples: 'Operação limitada com dupla revisão, expiração e trilha.', antiPattern: 'Dar privilégio amplo para acelerar a capacitação.',
    metric: 'pessoas preparadas bloqueadas e operações supervisionadas concluídas', successCriterion: 'a próxima pessoa preparada executa uma operação limitada com revisão e trilha sem privilégio permanente',
  },
  'aprendizado-sem-oportunidade-pratica': {
    mechanism: 'A organização oferece conteúdo, mas reserva o trabalho real às pessoas já experientes, eliminando a oportunidade de aplicar, receber feedback e formar julgamento.',
    constraintKind: 'process', plainExplanation: 'A pessoa estudou, mas nunca recebe uma parte segura do trabalho para praticar.',
    solutionKind: 'practice', solutionClass: 'Aprendizagem ligada a uma tarefa real com apoio', matureReference: 'Prática deliberada / aprendizagem aplicada',
    whyItWorks: 'Conhecimento recebe contexto, feedback e consequência observável.', doesNotSolve: 'Não ajuda quando carga ou acesso impedem a prática.',
    examples: 'Tarefa reduzida conduzida pela pessoa aprendiz com revisão próxima.', antiPattern: 'Ampliar a trilha de cursos sem mudar a distribuição do trabalho.',
    metric: 'pessoas capacitadas que aplicaram em tarefa real e ajuda necessária', successCriterion: 'a próxima pessoa capacitada conduz uma tarefa real pequena e incorpora o feedback recebido',
  },
  'competencia-dependente-de-fornecedor': {
    mechanism: 'O fornecedor conserva decisão e execução críticas; o time acompanha entregas, mas não recebe responsabilidade por um caso equivalente antes do aceite.',
    constraintKind: 'structure', plainExplanation: 'O parceiro entrega, porém o time ainda não consegue repetir ou mudar o que recebeu.',
    solutionKind: 'policy', solutionClass: 'Transferência verificável de capacidade no contrato e no trabalho', matureReference: 'Team Topologies / gestão de fornecedores',
    whyItWorks: 'Aceite passa a exigir execução interna observável, não apenas documentação entregue.', doesNotSolve: 'Não elimina fornecedor necessário por escala ou especialidade.',
    examples: 'Próxima mudança conduzida pelo time com apoio do parceiro.', antiPattern: 'Aceitar workshop e documentos como prova de autonomia.',
    metric: 'mudanças equivalentes conduzidas internamente e dependência do fornecedor para decisão', successCriterion: 'o time conduz a próxima mudança equivalente e o fornecedor atua apenas como apoio e revisão',
  },
  'aprendizado-impedido-por-carga': {
    mechanism: 'Toda capacidade disponível já está comprometida com entregas e urgências, então ensinar e praticar sempre perde para devolver o caso à pessoa mais rápida.',
    constraintKind: 'priority', plainExplanation: 'Há quem ensine e quem aprenda, mas ninguém consegue parar o trabalho suficiente para fazer isso acontecer.',
    solutionKind: 'policy', solutionClass: 'Capacidade protegida com redução temporária de escopo', matureReference: 'Lean / Accelerate',
    whyItWorks: 'A decisão torna explícito qual entrega cede espaço para reduzir dependência futura.', doesNotSolve: 'Não cria experiência inexistente nem acesso seguro.',
    examples: 'Diminuir um lote para executar em colaboração sem estender jornada.', antiPattern: 'Adicionar meta de capacitação sem retirar compromisso.',
    metric: 'aplicações canceladas por urgência e trabalho devolvido ao especialista', successCriterion: 'a próxima aplicação acompanhada termina dentro da capacidade normal com redução explícita de outro escopo',
  },
  'capacitacao-medida-por-presenca': {
    mechanism: 'O programa encerra ao registrar presença, conclusão ou satisfação antes de observar uma demanda equivalente executada no trabalho.',
    constraintKind: 'process', plainExplanation: 'Sabemos quem fez o curso, mas não se alguém passou a executar melhor ou com menos ajuda.',
    solutionKind: 'practice', solutionClass: 'Validação da aprendizagem por execução equivalente', matureReference: 'Prática deliberada',
    whyItWorks: 'A decisão de manter ou mudar o programa usa comportamento e resultado.', doesNotSolve: 'Não culpa a pessoa quando acesso, carga ou desenho impedem aplicação.',
    examples: 'Comparar conclusão, erros, ajuda e tempo numa tarefa posterior.', antiPattern: 'Usar certificado ou satisfação como prova de capacidade.',
    metric: 'participantes que aplicaram, ajuda necessária e erros na tarefa equivalente', successCriterion: 'a próxima revisão do programa usa execução real para manter, mudar ou interromper o conteúdo',
  },
  'matriz-de-competencia-sem-aplicacao': {
    mechanism: 'A avaliação registra conhecimento declarado sem mudar responsabilidade nem oferecer trabalho capaz de confirmar execução independente.',
    constraintKind: 'governance', plainExplanation: 'A planilha mostra mais habilidade, mas as mesmas pessoas continuam recebendo todo trabalho difícil.',
    solutionKind: 'practice', solutionClass: 'Validação de habilidade por responsabilidade observável', matureReference: 'Aprendizagem aplicada',
    whyItWorks: 'A classificação passa a refletir decisões e tarefas realmente conduzidas.', doesNotSolve: 'Não transforma a matriz em ranking individual nem dispensa apoio.',
    examples: 'Validar um item declarado em tarefa real com critério seguro.', antiPattern: 'Aumentar granularidade da matriz sem redistribuir trabalho.',
    metric: 'habilidades declaradas sem aplicação e distribuição das tarefas críticas', successCriterion: 'uma habilidade declarada é confirmada ou revista após a próxima tarefa equivalente',
  },
  'desenvolvimento-reforca-especialista': {
    mechanism: 'Ao primeiro risco de prazo, a pessoa especialista corrige ou retoma o trabalho; o sistema aprende que colaboração é mais lenta e volta a concentrar o próximo caso.',
    constraintKind: 'incentive', plainExplanation: 'A pessoa começa a aprender, mas o especialista assume quando aparece pressão.',
    solutionKind: 'practice', solutionClass: 'Colaboração com escopo reduzido sem retomada da execução', matureReference: 'Team Topologies / prática deliberada',
    whyItWorks: 'Preserva feedback próximo enquanto a pessoa aprendiz continua responsável pelo caso menor.', doesNotSolve: 'Não recomenda aceitar risco alto sem revisão.',
    examples: 'Reduzir escopo, parear e deixar a pessoa aprendiz concluir.', antiPattern: 'Especialista corrige silenciosamente e entrega no lugar da pessoa.',
    metric: 'casos retomados pelo especialista e partes concluídas pela pessoa aprendiz', successCriterion: 'no próximo caso, a pessoa aprendiz conclui o escopo reduzido e o especialista limita-se a apoiar e revisar',
  },
};

const sourceFallback: Record<string, Omit<SolutionGuidance, 'mechanism' | 'plainExplanation'>> = {
  'Continuous Delivery': {
    constraintKind: 'process', solutionKind: 'practice', solutionClass: 'Lote pequeno com feedback reproduzível no caminho da mudança',
    matureReference: 'Continuous Delivery', whyItWorks: 'O erro aparece cedo, enquanto ainda cabe reverter.',
    doesNotSolve: 'Não reorganiza times nem cria autonomia de plataforma.', examples: 'Verificação e integração frequentes — classe de prática, não a marca da esteira.',
    antiPattern: 'Instalar ferramenta e manter o lote grande.', metric: 'lead time até feedback e retrabalho da junção',
    successCriterion: 'a próxima mudança equivalente recebe feedback mais cedo sem aumento de falhas',
  },
  'Qualidade no fluxo': {
    constraintKind: 'process', solutionKind: 'policy', solutionClass: 'Risco tratado durante a construção, não numa fase no fim',
    matureReference: 'Qualidade no fluxo', whyItWorks: 'A verificação orienta quem ainda pode mudar o desenho.',
    doesNotSolve: 'Não cria competência de risco que o grupo não tem.', examples: 'Critério de pronto com evidência proporcional.',
    antiPattern: 'Mais fila de QA no fim do ciclo.', metric: 'espera na verificação e escapes depois do “pronto”',
    successCriterion: 'o risco nomeado entra antes do handoff final',
  },
  'Team Topologies': {
    constraintKind: 'structure', solutionKind: 'org-design', solutionClass: 'Fronteira e modo de interação alinhados ao fluxo',
    matureReference: 'Team Topologies', whyItWorks: 'A coordenação deixa de ser o produto.',
    doesNotSolve: 'Não remove acoplamento técnico que obriga mudança conjunta.', examples: 'Time de fluxo, plataforma ou colaboração temporária nomeada.',
    antiPattern: 'Reorganizar o organograma sem nomear o resultado da jornada.', metric: 'espera na passagem e grupos envolvidos na mesma mudança',
    successCriterion: 'uma passagem recorrente diminui ou ganha dono de resultado',
  },
  'Well-Architected / platform engineering': {
    constraintKind: 'platform', solutionKind: 'platform-capability', solutionClass: 'Caminho suportado com guardrail, não fila artesanal',
    matureReference: 'Well-Architected / platform engineering', whyItWorks: 'O consumidor conclui sem o herói da plataforma.',
    doesNotSolve: 'Não autoriza acesso irrestrito.', examples: 'Self-service da operação repetida — família de plataforma, sem pontuar portal.',
    antiPattern: 'Criar time de plataforma que só opera tickets.', metric: 'tempo do pedido recorrente e dependência do especialista',
    successCriterion: 'o pedido mais repetido tem caminho com tempo observável',
  },
  'Well-Architected — Security': {
    constraintKind: 'autonomy', solutionKind: 'policy', solutionClass: 'Identidade com escopo, validade e trilha',
    matureReference: 'Well-Architected — Security', whyItWorks: 'A urgência deixa de ser um favor pessoal.',
    doesNotSolve: 'Não descreve a ameaça se o grupo não a nomeou.', examples: 'Acesso mínimo e revogação — não o produto de cofre como maturidade.',
    antiPattern: 'Comprar cofre e manter senha no chat.', metric: 'espera por acesso e concessões sem expiração',
    successCriterion: 'o pedido frequente ganha expiração e trilha',
  },
  'Lean / Accelerate': {
    constraintKind: 'incentive', solutionKind: 'policy', solutionClass: 'Limitar trabalho em andamento e reconhecer efeito ponta a ponta',
    matureReference: 'Lean / Accelerate', whyItWorks: 'A espera deixa de ser mascarada por ocupação.',
    doesNotSolve: 'Não remove a dependência externa.', examples: 'WIP e lead time no ciclo de decisão.',
    antiPattern: 'Meta de itens iniciados ou de ocupação individual.', metric: 'tempo ponta a ponta e itens iniciados sob bloqueio',
    successCriterion: 'a próxima decisão usa espera e resultado, não só volume iniciado',
  },
  'Governança habilitadora': {
    constraintKind: 'process', solutionKind: 'policy', solutionClass: 'Controle que distingue risco e muda decisão com evidência',
    matureReference: 'Governança habilitadora', whyItWorks: 'O portão para de inflar o que é seguro.',
    doesNotSolve: 'Não substitui verificação técnica ausente.', examples: 'Classes de risco e guardrail na classe baixa.',
    antiPattern: 'Abolir controle sem nomear o risco.', metric: 'espera no controle e decisões que ele realmente alterou',
    successCriterion: 'caso de baixo risco flui mais rápido com evidência preservada no alto risco',
  },
  'SRE / blameless postmortem': {
    constraintKind: 'skill', solutionKind: 'practice', solutionClass: 'Ciclo detectar–mitigar–aprender sem culpa individual',
    matureReference: 'SRE / blameless postmortem', whyItWorks: 'A recorrência vira mudança no sistema, não no tom de voz.',
    doesNotSolve: 'Não cria o sinal se a jornada não está instrumentada.', examples: 'Análise curta com uma mudança verificável.',
    antiPattern: 'Blameless no nome e ação só sobre a pessoa.', metric: 'tempo até mitigar e recorrência da mesma classe',
    successCriterion: 'o próximo evento equivalente é detectado ou evitado mais cedo',
  },
  'Arquitetura evolutiva / DDD': {
    constraintKind: 'architecture', solutionKind: 'practice', solutionClass: 'Limite e significado explícitos na mudança que atravessa grupos',
    matureReference: 'Arquitetura evolutiva / DDD', whyItWorks: 'O custo deixa de ser coordenação implícita.',
    doesNotSolve: 'Não redesenha o organograma.', examples: 'Exemplo compartilhado da jornada e contrato no limite.',
    antiPattern: 'Glossário futuro no lugar do limite da mudança atual.', metric: 'grupos envolvidos e espera de coordenação na próxima mudança equivalente',
    successCriterion: 'a próxima mudança atravessa o limite com menos reconciliação de significado',
  },
  'Discovery e evidência de uso': {
    constraintKind: 'process', solutionKind: 'practice', solutionClass: 'Evidência de uso com poder de reabrir o investimento',
    matureReference: 'Discovery e evidência de uso', whyItWorks: 'A solução deixa de avançar só porque o escopo foi aceito.',
    doesNotSolve: 'Não cria autonomia se o patrocínio não pode ser contestado.', examples: 'Menor teste reversível da hipótese principal.',
    antiPattern: 'Discovery que só detalha a solução já escolhida.', metric: 'decisões alteradas por evidência e trabalho parado por hipótese invalidada',
    successCriterion: 'a próxima revisão usa efeito observado, não só o plano concluído',
  },
  'Melhoria contínua': {
    constraintKind: 'incentive', solutionKind: 'practice', solutionClass: 'Dono, capacidade e revisão de efeito para uma mudança',
    matureReference: 'Lean / melhoria contínua', whyItWorks: 'O aprendizado compete por tempo real, não só por discurso.',
    doesNotSolve: 'Não remove bloqueio de autonomia, plataforma ou estrutura.', examples: 'Uma ação com critério e data — não cerimônia extra.',
    antiPattern: 'Lista longa de melhorias sem parar trabalho que consome a capacidade.', metric: 'ações com efeito revisado e recorrência do padrão escolhido',
    successCriterion: 'a ação é revista por efeito e reduz a recorrência no recorte, não apenas concluída',
  },
};

export function guidanceFor(pattern: string, foundation?: FoundationRef, title = ''): SolutionGuidance {
  const known = explicit[pattern];
  if (known) return known;
  const fallback = sourceFallback[foundation?.source ?? ''] ?? sourceFallback['Melhoria contínua']!;
  const effect = lowerFirst(title || pattern);
  if (foundation?.source === 'Melhoria contínua') {
    return {
      ...fallback,
      mechanism: `“${effect}” se reproduz porque o ciclo de melhoria não reserva dono, capacidade e revisão de efeito para essa classe de problema.`,
      plainExplanation: `O grupo reconhece “${effect}”, mas a mudança não compete por tempo, dono e critério. Sem isso, a conversa se repete e o sistema não muda.`,
    };
  }
  return {
    ...fallback,
    mechanism: fallbackMechanism(foundation?.source) + (title ? ` Neste recorte, o efeito observado é: ${effect}.` : ''),
    plainExplanation: `${fallbackMechanism(foundation?.source)} Em linguagem cotidiana: ${effect}. A classe de solução abaixo ataca essa restrição; ferramenta só entra como referência, nunca como nota.`,
  };
}

export function causeFromGuidance(guidance: SolutionGuidance, title: string): string {
  const escaped = title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  if (new RegExp(escaped, 'i').test(guidance.mechanism)) return guidance.mechanism;
  return `${guidance.mechanism} Neste recorte, o efeito observado é: ${lowerFirst(title)}.`;
}

export function allowsImprovementFoundation(pattern: string): boolean {
  const known = explicit[pattern];
  if (!known) return true;
  return /melhoria contínua/i.test(known.matureReference);
}

export const trunkGuidancePatterns = Object.keys(explicit);

export function hasExplicitGuidance(pattern: string): boolean {
  return Object.hasOwn(explicit, pattern);
}

function fallbackMechanism(source?: string): string {
  const causes: Record<string, string> = {
    'Continuous Delivery': 'O caminho de mudança não produz feedback pequeno, frequente e reproduzível sob as condições observadas.',
    'Qualidade no fluxo': 'O risco entra tarde ou depende de uma etapa especializada, impedindo feedback durante a construção.',
    'SRE / blameless postmortem': 'Impacto, responsabilidade, diagnóstico e aprendizado não formam um ciclo operacional contínuo.',
    'Team Topologies': 'Fronteiras, prioridades ou carga cognitiva exigem coordenação fora do fluxo para concluir o trabalho.',
    'Governança habilitadora': 'O controle não diferencia risco com evidências capazes de mudar o caminho ou a decisão.',
    'Well-Architected / platform engineering': 'A capacidade depende de intervenção especializada em vez de um caminho suportado e repetível.',
    'Well-Architected — Security': 'Identidade ou acesso dependem de concessão artesanal sem escopo, validade e trilha adequados.',
    'Lean / Accelerate': 'Incentivos e capacidade favorecem iniciar ou concluir trabalho, sem reconciliar resultado e custo de atraso.',
    'Arquitetura evolutiva / DDD': 'O limite ou significado compartilhado permanece implícito e transfere custo para coordenação e mudanças futuras.',
    'Dados como produto': 'O significado ou contrato do dado muda sem ownership e compatibilidade visíveis aos consumidores.',
    'Discovery e evidência de uso': 'A experiência entra depois da decisão e não possui evidência com poder para reabrir o investimento.',
    'Data literacy / SRE': 'A decisão usa um agregado sem considerar denominador, distribuição e incerteza do recorte.',
    'Resilience engineering / SRE': 'Espera, repetição e isolamento da dependência não foram definidos pelo impacto aceitável.',
    'Uso responsável de assistência': 'A assistência entra no fluxo sem supervisão, rastreabilidade ou proteção proporcional ao risco.',
  };
  return causes[source ?? ''] ?? 'A condição observada permanece sem um mecanismo estável de feedback e revisão de efeito.';
}

function lowerFirst(value: string): string {
  return value.charAt(0).toLocaleLowerCase('pt-BR') + value.slice(1).replace(/[.]$/, '');
}
