import type { DatabaseSync } from 'node:sqlite';

export function applyMigrations(db: DatabaseSync): void {
  db.exec(`
    CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
    CREATE TABLE projects (id TEXT PRIMARY KEY, public_id TEXT UNIQUE NOT NULL, name TEXT NOT NULL, admin_secret_hash TEXT NOT NULL, minimum_group_size INTEGER NOT NULL DEFAULT 5, created_at TEXT NOT NULL);
    CREATE TABLE organization_units (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), parent_id TEXT REFERENCES organization_units(id), name TEXT NOT NULL, unit_type TEXT NOT NULL, path TEXT NOT NULL);
    CREATE INDEX idx_units_project ON organization_units(project_id);
    CREATE TABLE invitation_batches (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), unit_id TEXT NOT NULL REFERENCES organization_units(id), profile TEXT NOT NULL, quantity INTEGER NOT NULL, created_at TEXT NOT NULL, reissued_from TEXT UNIQUE REFERENCES invitation_batches(id));
    CREATE INDEX idx_batches_project ON invitation_batches(project_id, created_at);
    CREATE TABLE invitations (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), unit_id TEXT NOT NULL REFERENCES organization_units(id), profile TEXT NOT NULL, token_hash TEXT UNIQUE NOT NULL, status TEXT NOT NULL DEFAULT 'issued', expires_at TEXT NOT NULL, created_at TEXT NOT NULL, claimed_at TEXT, batch_id TEXT NOT NULL REFERENCES invitation_batches(id));
    CREATE INDEX idx_invitations_batch ON invitations(batch_id);
    CREATE TABLE assessment_graph_versions (version TEXT PRIMARY KEY, title TEXT NOT NULL, status TEXT NOT NULL, entry_node_key TEXT NOT NULL, published_at TEXT NOT NULL);
    CREATE TABLE assessment_nodes (graph_version TEXT NOT NULL REFERENCES assessment_graph_versions(version), node_key TEXT NOT NULL, node_type TEXT NOT NULL, title TEXT NOT NULL, scenario TEXT NOT NULL, prompt TEXT NOT NULL, position INTEGER NOT NULL, PRIMARY KEY (graph_version, node_key));
    CREATE TABLE assessment_options (graph_version TEXT NOT NULL, node_key TEXT NOT NULL, option_key TEXT NOT NULL, label TEXT NOT NULL, position INTEGER NOT NULL, PRIMARY KEY (graph_version, node_key, option_key), FOREIGN KEY (graph_version, node_key) REFERENCES assessment_nodes(graph_version, node_key));
    CREATE TABLE assessment_node_variants (graph_version TEXT NOT NULL, node_key TEXT NOT NULL, profile TEXT NOT NULL, title TEXT, scenario TEXT NOT NULL, prompt TEXT, PRIMARY KEY (graph_version, node_key, profile), FOREIGN KEY (graph_version, node_key) REFERENCES assessment_nodes(graph_version, node_key));
    CREATE TABLE assessment_edges (id TEXT PRIMARY KEY, graph_version TEXT NOT NULL, from_node_key TEXT NOT NULL, option_key TEXT, to_node_key TEXT NOT NULL, priority INTEGER NOT NULL DEFAULT 0, profile TEXT, FOREIGN KEY (graph_version, from_node_key) REFERENCES assessment_nodes(graph_version, node_key), FOREIGN KEY (graph_version, to_node_key) REFERENCES assessment_nodes(graph_version, node_key));
    CREATE TABLE assessment_signals (id TEXT PRIMARY KEY, graph_version TEXT NOT NULL, node_key TEXT NOT NULL, option_key TEXT NOT NULL, capability TEXT NOT NULL, pattern TEXT NOT NULL, weight INTEGER NOT NULL, detail_capabilities TEXT NOT NULL, evidence_layer TEXT NOT NULL, constraint_kind TEXT NOT NULL, FOREIGN KEY (graph_version, node_key, option_key) REFERENCES assessment_options(graph_version, node_key, option_key));
    CREATE TABLE inference_model_versions (version TEXT PRIMARY KEY, graph_version TEXT NOT NULL, status TEXT NOT NULL, policy_json TEXT NOT NULL, published_at TEXT NOT NULL);
    CREATE TABLE diagnostic_hypotheses (model_version TEXT NOT NULL REFERENCES inference_model_versions(version), family_key TEXT NOT NULL, capability TEXT NOT NULL, hypothesis_key TEXT NOT NULL, label TEXT NOT NULL, prior REAL NOT NULL CHECK(prior > 0 AND prior < 1), PRIMARY KEY(model_version, family_key, hypothesis_key));
    CREATE TABLE evidence_likelihoods (model_version TEXT NOT NULL, family_key TEXT NOT NULL, pattern TEXT NOT NULL, evidence_group TEXT NOT NULL, hypothesis_key TEXT NOT NULL, likelihood REAL NOT NULL CHECK(likelihood > 0 AND likelihood < 1), PRIMARY KEY(model_version, family_key, pattern, hypothesis_key), FOREIGN KEY(model_version, family_key, hypothesis_key) REFERENCES diagnostic_hypotheses(model_version, family_key, hypothesis_key));
    CREATE TABLE question_observations (model_version TEXT NOT NULL REFERENCES inference_model_versions(version), node_key TEXT NOT NULL, profiles_json TEXT NOT NULL, applicability_patterns_json TEXT NOT NULL, cost REAL NOT NULL CHECK(cost >= 0 AND cost <= 1), PRIMARY KEY(model_version, node_key));
    CREATE TABLE intervention_prerequisites (model_version TEXT NOT NULL REFERENCES inference_model_versions(version), intervention_key TEXT NOT NULL, hypothesis_key TEXT NOT NULL, prerequisite_key TEXT NOT NULL, kind TEXT NOT NULL, PRIMARY KEY(model_version, intervention_key, prerequisite_key));
    CREATE TABLE participations (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), unit_id TEXT NOT NULL REFERENCES organization_units(id), profile TEXT NOT NULL, resume_hash TEXT UNIQUE NOT NULL, graph_version TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'in_progress', current_node TEXT NOT NULL, created_at TEXT NOT NULL, completed_at TEXT);
    CREATE TABLE responses (id TEXT PRIMARY KEY, participation_id TEXT NOT NULL REFERENCES participations(id), node_id TEXT NOT NULL, option_id TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(participation_id, node_id));
    CREATE TABLE inference_snapshots (id TEXT PRIMARY KEY, model_version TEXT NOT NULL REFERENCES inference_model_versions(version), participation_id TEXT NOT NULL REFERENCES participations(id), family_key TEXT NOT NULL, posterior_json TEXT NOT NULL, selected_question_key TEXT, selection_reason TEXT NOT NULL, created_at TEXT NOT NULL);
    INSERT INTO schema_migrations (version, applied_at) VALUES (15, datetime('now'));
  `);
}
